/**
 * PDF Parser & Modifier showcase — round-trip parsing and modification.
 */

import { resolve } from 'path';
import {
    buildPDFBytes, buildDocumentPDFBytes,
    openPdf, createModifier,
} from '../../src/index.js';
import type { PdfParams, DocumentParams, PdfValue } from '../../src/index.js';
import type { GenerateContext } from '../helpers/io.js';

export async function generate(ctx: GenerateContext): Promise<void> {
    // ── 1. Generate → Parse → Verify (table PDF) ───────────────
    {
        const params: PdfParams = {
            title: 'Parser Demo – Original Table',
            infoItems: [{ label: 'Generator', value: 'pdfnative parser showcase' }],
            balanceText: 'Balance: $5,000.00',
            countText: '5 transactions',
            headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
            rows: [
                { cells: ['01/15', 'Grocery Store', 'Food', '-$45.00', ''], type: 'debit', pointed: false },
                { cells: ['01/16', 'Salary', 'Income', '+$3,000.00', 'X'], type: 'credit', pointed: true },
                { cells: ['01/17', 'Electric Bill', 'Utilities', '-$120.00', ''], type: 'debit', pointed: false },
                { cells: ['01/18', 'Freelance', 'Income', '+$800.00', 'X'], type: 'credit', pointed: true },
                { cells: ['01/19', 'Restaurant', 'Food', '-$65.00', ''], type: 'debit', pointed: false },
            ],
            footerText: 'Generated by pdfnative parser showcase',
        };

        const bytes = buildPDFBytes(params, { compress: false });
        const reader = openPdf(bytes);

        // Verify the parser can read our own output
        const pageCount = reader.pageCount;
        const title = reader.getInfo()?.get('Title') ?? '(unknown)';

        ctx.writeSafe(
            resolve(ctx.outputDir, 'parser', 'parser-original.pdf'),
            `parser-original.pdf (${pageCount} pages, title="${title}")`,
            bytes,
        );
    }

    // ── 2. Generate → Parse → Modify → Save ────────────────────
    {
        const params: PdfParams = {
            title: 'Parser Demo – Modified Table',
            infoItems: [{ label: 'Version', value: 'Before modification' }],
            balanceText: 'Balance: $1,000.00',
            countText: '2 transactions',
            headers: ['Date', 'Description', 'Amount'],
            rows: [
                { cells: ['02/01', 'Initial deposit', '+$1,000.00'], type: 'credit', pointed: false },
                { cells: ['02/02', 'Service fee', '-$25.00'], type: 'debit', pointed: false },
            ],
            footerText: 'Original document',
        };

        const original = buildPDFBytes(params, { compress: false });
        const reader = openPdf(original);
        const mod = createModifier(reader);

        // Add custom metadata object
        const metaDict = new Map<string, PdfValue>();
        metaDict.set('Type', 'Metadata');
        metaDict.set('ModifiedBy', 'pdfnative modifier');
        metaDict.set('Revision', 2);
        mod.addObject(metaDict);

        const modified = mod.save();

        const reader2 = openPdf(modified);
        ctx.writeSafe(
            resolve(ctx.outputDir, 'parser', 'parser-modified.pdf'),
            `parser-modified.pdf (${reader2.pageCount} pages, incremental update)`,
            modified,
        );
    }

    // ── 3. Document PDF → Parse → Verify ────────────────────────
    {
        const params: DocumentParams = {
            title: 'Parser Demo – Document',
            blocks: [
                { type: 'heading', text: 'PDF Parsing Capabilities', level: 1 },
                { type: 'paragraph', text: 'This document was generated, then parsed back by the pdfnative parser module to verify round-trip correctness.' },
                { type: 'heading', text: 'Supported Features', level: 2 },
                { type: 'list', style: 'bullet', items: [
                    'Traditional xref table parsing',
                    'Cross-reference stream parsing',
                    'Incremental update (/Prev chain) following',
                    'FlateDecode decompression (pure JS + Node.js native)',
                    'Indirect object resolution with caching',
                    'Page tree flattening',
                    'Info dictionary extraction',
                    'Incremental modification (non-destructive save)',
                ] },
                { type: 'heading', text: 'Round-Trip Verification', level: 2 },
                { type: 'paragraph', text: 'The parser successfully extracted the page count, catalog dictionary, and document info from this PDF after generation.' },
            ],
            footerText: 'pdfnative parser showcase',
        };

        const bytes = buildDocumentPDFBytes(params, { compress: false });
        const reader = openPdf(bytes);

        ctx.writeSafe(
            resolve(ctx.outputDir, 'parser', 'parser-document.pdf'),
            `parser-document.pdf (${reader.pageCount} pages, document builder round-trip)`,
            bytes,
        );
    }
}
