import { describe, it, expect } from 'vitest';
import { buildDocumentPDF, buildDocumentPDFBytes, wrapText } from '../../src/core/pdf-document.js';
import { createEncodingContext } from '../../src/fonts/encoding.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';
import type { FontData, FontEntry } from '../../src/types/pdf-types.js';

/** Minimal mock FontData for Unicode path testing. */
function makeMockFontData(): FontData {
    return {
        metrics: { unitsPerEm: 1000, numGlyphs: 10, defaultWidth: 500, ascent: 800, descent: -200, bbox: [0, -200, 600, 800], capHeight: 700, stemV: 50 },
        fontName: 'TestFont',
        cmap: { 65: 1, 66: 2, 32: 3, 48: 4, 49: 5 },
        defaultWidth: 500,
        widths: { 1: 600, 2: 700, 3: 250, 4: 500, 5: 500 },
        pdfWidthArray: '1 [600] 2 [700] 3 [250] 4 [500] 5 [500]',
        ttfBase64: 'AAAAAAAAAA==',
        gsub: {},
        markAnchors: null,
        mark2mark: null,
    };
}

function makeMinimalParams(overrides?: Partial<DocumentParams>): DocumentParams {
    return {
        title: 'Test Document',
        blocks: [
            { type: 'paragraph', text: 'Hello world' },
        ],
        footerText: 'Generated by pdfnative',
        ...overrides,
    };
}

// ── wrapText ─────────────────────────────────────────────────────────

describe('wrapText', () => {
    const enc = createEncodingContext([]);

    it('should return single line for short text', () => {
        const lines = wrapText('Hello', 500, 10, enc);
        expect(lines).toEqual(['Hello']);
    });

    it('should wrap long text into multiple lines', () => {
        const longText = 'This is a fairly long paragraph that should definitely be wrapped into multiple lines when rendered in a PDF document with limited width';
        const lines = wrapText(longText, 150, 10, enc);
        expect(lines.length).toBeGreaterThan(1);
    });

    it('should return empty string line for empty input', () => {
        const lines = wrapText('', 200, 10, enc);
        expect(lines).toEqual(['']);
    });

    it('should return original text when maxWidth is zero', () => {
        const lines = wrapText('Hello world', 0, 10, enc);
        expect(lines).toEqual(['Hello world']);
    });

    it('should handle single word that exceeds width', () => {
        const lines = wrapText('Supercalifragilisticexpialidocious', 10, 10, enc);
        expect(lines).toEqual(['Supercalifragilisticexpialidocious']);
    });

    it('should split on spaces', () => {
        const lines = wrapText('A B C D E', 20, 10, enc);
        expect(lines.length).toBeGreaterThan(1);
        for (const line of lines) {
            expect(line.trim()).toBe(line);
        }
    });
});

// ── buildDocumentPDF — basic structure ────────────────────────────────

describe('buildDocumentPDF', () => {
    it('should produce a valid PDF starting with %PDF-1.4', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toMatch(/^%PDF-1\.4/);
    });

    it('should end with %%EOF', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toMatch(/%%EOF$/);
    });

    it('should contain binary header marker', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('%\xE2\xE3\xCF\xD3');
    });

    it('should contain catalog object', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('/Type /Catalog');
        expect(result).toContain('/Pages 2 0 R');
    });

    it('should contain pages object', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('/Type /Pages');
        expect(result).toContain('/Count 1');
    });

    it('should contain Helvetica font references', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('/BaseFont /Helvetica');
        expect(result).toContain('/BaseFont /Helvetica-Bold');
    });

    it('should contain xref table', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('xref\n');
        expect(result).toContain('startxref\n');
    });

    it('should contain trailer with /Root and /Size', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('trailer');
        expect(result).toContain('/Root 1 0 R');
        expect(result).toMatch(/\/Size \d+/);
    });

    it('should have valid xref offsets', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        const xrefMatch = result.match(/xref\n0 (\d+)\n([\s\S]+?)trailer/);
        expect(xrefMatch).not.toBeNull();
        const entries = xrefMatch![2].trim().split('\n');
        expect(entries[0]).toMatch(/0000000000 65535 f/);
        for (let i = 1; i < entries.length; i++) {
            const offsetMatch = entries[i].match(/^(\d{10}) 00000 n/);
            expect(offsetMatch).not.toBeNull();
            const off = parseInt(offsetMatch![1], 10);
            expect(result.substring(off, off + `${i} 0 obj`.length)).toBe(`${i} 0 obj`);
        }
    });
});

// ── Block types ──────────────────────────────────────────────────────

describe('buildDocumentPDF heading blocks', () => {
    it('should render heading text in the PDF', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Chapter One', level: 1 }],
        }));
        expect(result).toContain('Chapter One');
    });

    it('should render level 2 headings', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Subsection', level: 2 }],
        }));
        expect(result).toContain('Subsection');
    });

    it('should render level 3 headings', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Detail', level: 3 }],
        }));
        expect(result).toContain('Detail');
    });

    it('should apply custom heading color', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Red Title', level: 1, color: '1.000 0.000 0.000' }],
        }));
        expect(result).toContain('1.000 0.000 0.000 rg');
    });

    it('should accept heading hex color', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Blue Title', level: 1, color: '#2563EB' }],
        }));
        expect(result).toContain('0.145 0.388 0.922 rg');
    });
});

describe('buildDocumentPDF paragraph blocks', () => {
    it('should render paragraph text', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'paragraph', text: 'This is a test paragraph.' }],
        }));
        expect(result).toContain('This is a test paragraph.');
    });

    it('should render long paragraph with wrapping', () => {
        const longText = Array(50).fill('word').join(' ');
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'paragraph', text: longText }],
        }));
        expect(result).toMatch(/^%PDF-1\.4/);
        expect(result).toContain('word');
    });

    it('should accept custom paragraph color', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'paragraph', text: 'Green text', color: '0.000 1.000 0.000' }],
        }));
        expect(result).toContain('0.000 1.000 0.000 rg');
    });

    it('should accept paragraph hex color', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'paragraph', text: 'Red text', color: '#FF0000' }],
        }));
        expect(result).toContain('1 0 0 rg');
    });
});

describe('buildDocumentPDF list blocks', () => {
    it('should render bullet list items', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'list', items: ['Item A', 'Item B', 'Item C'], style: 'bullet' }],
        }));
        expect(result).toContain('Item A');
        expect(result).toContain('Item B');
        expect(result).toContain('Item C');
    });

    it('should render numbered list items', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'list', items: ['First', 'Second'], style: 'numbered' }],
        }));
        expect(result).toContain('First');
        expect(result).toContain('Second');
    });
});

describe('buildDocumentPDF table blocks', () => {
    it('should render inline table', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{
                type: 'table',
                headers: ['Name', 'Value'],
                rows: [
                    { cells: ['Alpha', '100'], type: 'credit', pointed: false },
                    { cells: ['Beta', '200'], type: 'debit', pointed: false },
                ],
            }],
        }));
        expect(result).toContain('Alpha');
        expect(result).toContain('Beta');
    });
});

describe('buildDocumentPDF spacer and page break', () => {
    it('should handle spacer blocks without error', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [
                { type: 'paragraph', text: 'Before spacer' },
                { type: 'spacer', height: 50 },
                { type: 'paragraph', text: 'After spacer' },
            ],
        }));
        expect(result).toContain('Before spacer');
        expect(result).toContain('After spacer');
    });

    it('should create multiple pages with page break', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [
                { type: 'paragraph', text: 'Page one content' },
                { type: 'pageBreak' },
                { type: 'paragraph', text: 'Page two content' },
            ],
        }));
        const pageCount = (result.match(/\/Type \/Page /g) || []).length;
        expect(pageCount).toBe(2);
    });
});

// ── Pagination ───────────────────────────────────────────────────────

describe('buildDocumentPDF pagination', () => {
    it('should auto-paginate when content exceeds page height', () => {
        const blocks = Array.from({ length: 80 }, (_, i) => ({
            type: 'paragraph' as const,
            text: `Paragraph number ${i + 1} with enough text to take up space on the page.`,
        }));
        const result = buildDocumentPDF(makeMinimalParams({ blocks }));
        const pageCount = (result.match(/\/Type \/Page /g) || []).length;
        expect(pageCount).toBeGreaterThan(1);
    });

    it('should handle empty blocks array', () => {
        const result = buildDocumentPDF(makeMinimalParams({ blocks: [] }));
        expect(result).toMatch(/^%PDF-1\.4/);
        expect(result).toMatch(/%%EOF$/);
    });
});

// ── Mixed blocks ─────────────────────────────────────────────────────

describe('buildDocumentPDF mixed blocks', () => {
    it('should render a document with all block types', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            title: 'Full Document',
            blocks: [
                { type: 'heading', text: 'Introduction', level: 1 },
                { type: 'paragraph', text: 'Welcome to this document.' },
                { type: 'heading', text: 'Details', level: 2 },
                { type: 'list', items: ['Point A', 'Point B'], style: 'bullet' },
                { type: 'spacer', height: 20 },
                { type: 'table', headers: ['Col1', 'Col2'], rows: [{ cells: ['X', 'Y'], type: 'credit', pointed: false }] },
                { type: 'heading', text: 'Conclusion', level: 3 },
                { type: 'paragraph', text: 'Thank you for reading.' },
            ],
            footerText: 'Page footer',
        }));
        expect(result).toContain('Introduction');
        expect(result).toContain('Welcome to this document.');
        expect(result).toContain('Details');
        expect(result).toContain('Point A');
        expect(result).toContain('Conclusion');
        expect(result).toContain('Thank you for reading.');
    });
});

// ── /Info dictionary ─────────────────────────────────────────────────

describe('buildDocumentPDF /Info dictionary', () => {
    it('should contain /Producer (pdfnative)', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toContain('/Producer (pdfnative)');
    });

    it('should contain /CreationDate', () => {
        const result = buildDocumentPDF(makeMinimalParams());
        expect(result).toMatch(/\/CreationDate \(D:\d{14}\)/);
    });

    it('should include /Title from params', () => {
        const result = buildDocumentPDF(makeMinimalParams({ title: 'My Doc' }));
        expect(result).toContain('/Title (My Doc)');
    });

    it('should include /Author from metadata', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            metadata: { author: 'John Doe' },
        }));
        expect(result).toContain('/Author (John Doe)');
    });

    it('should include /Subject from metadata', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            metadata: { subject: 'Test Subject' },
        }));
        expect(result).toContain('/Subject (Test Subject)');
    });

    it('should include /Keywords from metadata', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            metadata: { keywords: 'pdf, test' },
        }));
        expect(result).toContain('/Keywords (pdf, test)');
    });

    it('should escape special characters in metadata', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            metadata: { author: 'John (Jr) Doe\\Sr' },
        }));
        expect(result).toContain('/Author (John \\(Jr\\) Doe\\\\Sr)');
    });
});

// ── Input validation ─────────────────────────────────────────────────

describe('buildDocumentPDF input validation', () => {
    it('should throw when params is null', () => {
        expect(() => buildDocumentPDF(null as unknown as DocumentParams)).toThrow('params is required');
    });

    it('should throw when params is undefined', () => {
        expect(() => buildDocumentPDF(undefined as unknown as DocumentParams)).toThrow('params is required');
    });

    it('should throw when blocks is not an array', () => {
        expect(() => buildDocumentPDF({ blocks: 'bad' } as unknown as DocumentParams)).toThrow('params.blocks must be an array');
    });

    it('should throw when block count exceeds limit', () => {
        const blocks = Array.from({ length: 10_001 }, () => ({ type: 'spacer' as const, height: 1 }));
        expect(() => buildDocumentPDF({ blocks })).toThrow('exceeds safe limit');
    });
});

// ── buildDocumentPDFBytes ────────────────────────────────────────────

describe('buildDocumentPDFBytes', () => {
    it('should return Uint8Array', () => {
        const result = buildDocumentPDFBytes(makeMinimalParams());
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should start with %PDF-1.4 bytes', () => {
        const result = buildDocumentPDFBytes(makeMinimalParams());
        const header = String.fromCharCode(...result.slice(0, 9));
        expect(header).toBe('%PDF-1.4\n');
    });

    it('should have consistent length with string version', () => {
        const params = makeMinimalParams();
        const str = buildDocumentPDF(params);
        const bytes = buildDocumentPDFBytes(params);
        expect(bytes.length).toBe(str.length);
    });
});

// ── Tagged mode ──────────────────────────────────────────────────────

describe('buildDocumentPDF tagged mode', () => {
    it('should include StructTreeRoot when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/Type /StructTreeRoot');
    });

    it('should include /MarkInfo when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/MarkInfo << /Marked true >>');
    });

    it('should include XMP metadata when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/Type /Metadata');
        expect(result).toContain('pdfaid:part');
    });

    it('should include OutputIntent when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/Type /OutputIntent');
        expect(result).toContain('/S /GTS_PDFA1');
    });

    it('should include /StructParents on pages when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/StructParents 0');
    });

    it('should include marked content (BDC/EMC) when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('BDC');
        expect(result).toContain('EMC');
    });

    it('should include /ActualText on spans when tagged', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        expect(result).toContain('/ActualText');
    });

    it('should produce structure elements for headings', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'heading', text: 'Title', level: 1 }],
        }), { tagged: true });
        expect(result).toContain('/S /H1');
    });

    it('should produce /P structure elements for paragraphs', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'paragraph', text: 'Some text' }],
        }), { tagged: true });
        expect(result).toContain('/S /P');
    });

    it('should produce /L and /LI structure elements for lists', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{ type: 'list', items: ['A', 'B'], style: 'bullet' }],
        }), { tagged: true });
        expect(result).toContain('/S /L');
        expect(result).toContain('/S /LI');
    });

    it('should produce /Table structure elements for tables', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            blocks: [{
                type: 'table',
                headers: ['H1', 'H2'],
                rows: [{ cells: ['A', 'B'], type: 'credit', pointed: false }],
            }],
        }), { tagged: true });
        expect(result).toContain('/S /Table');
        expect(result).toContain('/S /TR');
    });

    it('should have valid xref offsets in tagged mode', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { tagged: true });
        const xrefMatch = result.match(/xref\n0 (\d+)\n([\s\S]+?)trailer/);
        expect(xrefMatch).not.toBeNull();
        const entries = xrefMatch![2].trim().split('\n');
        expect(entries[0]).toMatch(/0000000000 65535 f/);
        for (let i = 1; i < entries.length; i++) {
            const offsetMatch = entries[i].match(/^(\d{10}) 00000 n/);
            expect(offsetMatch).not.toBeNull();
            const off = parseInt(offsetMatch![1], 10);
            expect(result.substring(off, off + `${i} 0 obj`.length)).toBe(`${i} 0 obj`);
        }
    });
});

// ── Layout options ───────────────────────────────────────────────────

describe('buildDocumentPDF layout options', () => {
    it('should accept custom page dimensions', () => {
        const result = buildDocumentPDF(makeMinimalParams(), { pageWidth: 612, pageHeight: 792 });
        expect(result).toContain('612.00 792.00');
    });

    it('should support layout in params.layout', () => {
        const result = buildDocumentPDF(makeMinimalParams({
            layout: { pageWidth: 612, pageHeight: 792 },
        }));
        expect(result).toContain('612.00 792.00');
    });
});

// ── Unicode mode ─────────────────────────────────────────────────────

describe('buildDocumentPDF Unicode mode', () => {
    it('should embed CIDFont when fontEntries provided', () => {
        const fd = makeMockFontData();
        const fe: FontEntry = { fontData: fd, fontRef: '/F3', lang: 'test' };
        const result = buildDocumentPDF(makeMinimalParams({ fontEntries: [fe] }));
        expect(result).toContain('/Subtype /CIDFontType2');
        expect(result).toContain('/Encoding /Identity-H');
    });

    it('should contain ToUnicode CMap in Unicode mode', () => {
        const fd = makeMockFontData();
        const fe: FontEntry = { fontData: fd, fontRef: '/F3', lang: 'test' };
        const result = buildDocumentPDF(makeMinimalParams({ fontEntries: [fe] }));
        expect(result).toContain('/ToUnicode');
    });
});

// ── No title ─────────────────────────────────────────────────────────

describe('buildDocumentPDF without title', () => {
    it('should produce valid PDF when title is omitted', () => {
        const result = buildDocumentPDF({
            blocks: [{ type: 'paragraph', text: 'No title here' }],
        });
        expect(result).toMatch(/^%PDF-1\.4/);
        expect(result).toContain('No title here');
    });
});

// ── Backward compatibility ───────────────────────────────────────────

describe('backward compatibility', () => {
    it('should not affect existing buildPDF imports', async () => {
        const { buildPDF } = await import('../../src/core/pdf-builder.js');
        expect(typeof buildPDF).toBe('function');
    });

    it('should coexist with buildPDF in the same index', async () => {
        const idx = await import('../../src/index.js');
        expect(typeof idx.buildPDF).toBe('function');
        expect(typeof idx.buildDocumentPDF).toBe('function');
        expect(typeof idx.buildDocumentPDFBytes).toBe('function');
        expect(typeof idx.wrapText).toBe('function');
    });
});
