import { describe, it, expect } from 'vitest';
import { buildPDF, buildPDFBytes } from '../../src/core/pdf-builder.js';
import type { PdfParams, FontData, FontEntry } from '../../src/types/pdf-types.js';

/** Minimal mock FontData for Unicode path testing. */
function makeMockFontData(): FontData {
    return {
        metrics: { unitsPerEm: 1000, numGlyphs: 10, defaultWidth: 500, ascent: 800, descent: -200, bbox: [0, -200, 600, 800], capHeight: 700, stemV: 50 },
        fontName: 'TestFont',
        cmap: { 65: 1, 66: 2, 32: 3, 48: 4, 49: 5 },
        defaultWidth: 500,
        widths: { 1: 600, 2: 700, 3: 250, 4: 500, 5: 500 },
        pdfWidthArray: '1 [600] 2 [700] 3 [250] 4 [500] 5 [500]',
        ttfBase64: 'AAAAAAAAAA==', // 7 zero bytes — invalid TTF, subsetter will return original
        gsub: {},
        markAnchors: null,
        mark2mark: null,
    };
}

function makeMinimalParams(overrides?: Partial<PdfParams>): PdfParams {
    return {
        title: 'Test Report',
        infoItems: [{ label: 'Period', value: 'Jan 2026' }],
        balanceText: 'Balance: $100.00',
        countText: '2 items',
        headers: ['Date', 'Description', 'Amount'],
        rows: [
            { cells: ['01/01', 'Item A', '$50.00'], type: 'credit', pointed: false },
            { cells: ['01/02', 'Item B', '-$25.00'], type: 'debit', pointed: true },
        ],
        footerText: 'Generated by pdfnative',
        ...overrides,
    };
}

describe('buildPDF', () => {
    it('should produce a valid PDF string starting with %PDF-1.4', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toMatch(/^%PDF-1\.4/);
    });

    it('should end with %%EOF', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toMatch(/%%EOF$/);
    });

    it('should contain binary header marker', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('%\xE2\xE3\xCF\xD3');
    });

    it('should contain catalog object', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('/Type /Catalog');
        expect(result).toContain('/Pages 2 0 R');
    });

    it('should contain pages object', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('/Type /Pages');
        expect(result).toContain('/Count 1');
    });

    it('should contain Helvetica font references', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('/BaseFont /Helvetica');
        expect(result).toContain('/BaseFont /Helvetica-Bold');
        expect(result).toContain('/Encoding /WinAnsiEncoding');
    });

    it('should contain page content with title', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('Test Report');
    });

    it('should contain xref table', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('xref\n');
        expect(result).toContain('startxref\n');
    });

    it('should contain trailer with /Root and /Size', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('trailer');
        expect(result).toContain('/Root 1 0 R');
        expect(result).toMatch(/\/Size \d+/);
    });

    it('should have valid xref offsets pointing to obj declarations', () => {
        const result = buildPDF(makeMinimalParams());
        const xrefMatch = result.match(/xref\n0 (\d+)\n([\s\S]+?)trailer/);
        expect(xrefMatch).not.toBeNull();

        const entries = xrefMatch![2].trim().split('\n');
        // First entry is the free entry (0000000000 65535 f)
        expect(entries[0]).toMatch(/0000000000 65535 f/);

        // Each subsequent entry should point to a valid "N 0 obj" in the PDF
        for (let i = 1; i < entries.length; i++) {
            const offsetMatch = entries[i].match(/^(\d{10}) 00000 n/);
            expect(offsetMatch).not.toBeNull();
            const offset = parseInt(offsetMatch![1], 10);
            const objMarker = `${i} 0 obj`;
            expect(result.substring(offset, offset + objMarker.length)).toBe(objMarker);
        }
    });
});

// ── Header / Footer Templates ────────────────────────────────────────

describe('Header/Footer Templates (Table Builder)', () => {
    it('should render custom footer template text', () => {
        const result = buildPDF(makeMinimalParams(), {
            footerTemplate: { left: 'Custom Footer', right: 'Page {page} of {pages}' },
        });
        expect(result).toContain('Custom Footer');
        expect(result).toContain('Page 1 of 1');
    });

    it('should render footer center text', () => {
        const result = buildPDF(makeMinimalParams(), {
            footerTemplate: { center: 'Centered' },
        });
        expect(result).toContain('Centered');
    });

    it('should resolve {title} placeholder in footer', () => {
        const result = buildPDF(makeMinimalParams({ title: 'My Report' }), {
            footerTemplate: { left: '{title}' },
        });
        expect(result).toContain('My Report');
    });

    it('should resolve {date} placeholder', () => {
        const result = buildPDF(makeMinimalParams(), {
            footerTemplate: { left: '{date}' },
        });
        expect(result).toMatch(/\d{4}-\d{2}-\d{2}/);
    });

    it('should override footerText when footerTemplate is provided', () => {
        const result = buildPDF(
            makeMinimalParams({ footerText: 'Old Footer' }),
            { footerTemplate: { left: 'New Footer' } },
        );
        expect(result).toContain('New Footer');
    });

    it('should use footerText as backward compat when no template', () => {
        const result = buildPDF(makeMinimalParams({ footerText: 'Legacy Footer' }));
        expect(result).toContain('Legacy Footer');
        expect(result).toContain('1/1');
    });

    it('should render header template on each page', () => {
        // Create enough rows to span 2 pages
        const rows = Array.from({ length: 80 }, (_, i) => ({
            cells: [`${i}`, 'Description', 'Cat', '$10', ''],
            type: 'credit' as const,
            pointed: false,
        }));
        const result = buildPDF(makeMinimalParams({ rows }), {
            headerTemplate: { left: 'Header Text', right: '{page}/{pages}' },
        });
        const matches = result.match(/Header Text/g);
        expect(matches).not.toBeNull();
        expect(matches!.length).toBeGreaterThanOrEqual(2);
    });

    it('should render header with custom color', () => {
        const result = buildPDF(makeMinimalParams(), {
            headerTemplate: { left: 'Red Header', color: '#FF0000' },
        });
        expect(result).toContain('Red Header');
        expect(result).toContain('1 0 0 rg');
    });

    it('should produce valid PDF with header + footer templates', () => {
        const result = buildPDF(makeMinimalParams(), {
            headerTemplate: { left: 'Company', center: '{title}', right: '{date}' },
            footerTemplate: { left: 'Confidential', right: 'Page {page}/{pages}' },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toMatch(/%%EOF$/);
        expect(result).toContain('xref');
    });

    it('should handle header + footer + tagged mode', () => {
        const result = buildPDF(makeMinimalParams(), {
            tagged: true,
            headerTemplate: { left: 'Header' },
            footerTemplate: { right: '{page}/{pages}' },
        });
        expect(result).toContain('Header');
        expect(result).toContain('1/1');
        expect(result).toContain('/StructTreeRoot');
    });

    it('should handle empty template (no header/footer content)', () => {
        const result = buildPDF(makeMinimalParams(), { footerTemplate: {} });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toMatch(/%%EOF$/);
    });

    it('should adjust pagination when header reduces available height', () => {
        const rows = Array.from({ length: 60 }, (_, i) => ({
            cells: [`${i}`, 'Desc', 'Cat', '$10', ''],
            type: 'credit' as const,
            pointed: false,
        }));
        const resultNoHeader = buildPDF(makeMinimalParams({ rows }));
        const resultWithHeader = buildPDF(makeMinimalParams({ rows }), {
            headerTemplate: { left: 'Header' },
        });
        const noHeaderPages = (resultNoHeader.match(/\/Type \/Page /g) ?? []).length;
        const withHeaderPages = (resultWithHeader.match(/\/Type \/Page /g) ?? []).length;
        expect(withHeaderPages).toBeGreaterThanOrEqual(noHeaderPages);
    });
});

describe('buildPDFBytes', () => {
    it('should return Uint8Array', () => {
        const result = buildPDFBytes(makeMinimalParams());
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should start with %PDF-1.4 bytes', () => {
        const result = buildPDFBytes(makeMinimalParams());
        const header = String.fromCharCode(...result.slice(0, 9));
        expect(header).toBe('%PDF-1.4\n');
    });

    it('should have consistent length with string version', () => {
        const params = makeMinimalParams();
        const str = buildPDF(params);
        const bytes = buildPDFBytes(params);
        expect(bytes.length).toBe(str.length);
    });
});

describe('buildPDF pagination', () => {
    it('should create multiple pages for many rows', () => {
        const rows = Array.from({ length: 200 }, (_, i) => ({
            cells: [`${i}`, `Item ${i}`, `$${i}.00`],
            type: i % 2 === 0 ? 'credit' : 'debit',
            pointed: i % 5 === 0,
        }));
        const result = buildPDF(makeMinimalParams({ rows }));
        // Should have more than 1 page — count /Type /Page with space, not /Pages
        const pageCount = (result.match(/\/Type \/Page /g) || []).length;
        expect(pageCount).toBeGreaterThan(1);
    });

    it('should handle empty rows', () => {
        const result = buildPDF(makeMinimalParams({ rows: [] }));
        expect(result).toMatch(/^%PDF-1\.4/);
        expect(result).toMatch(/%%EOF$/);
    });

    it('should handle single row', () => {
        const result = buildPDF(makeMinimalParams({
            rows: [{ cells: ['01/01', 'Single', '$1.00'], type: 'credit', pointed: false }],
        }));
        expect(result).toContain('/Count 1');
    });
});

describe('buildPDF with layout options', () => {
    it('should accept custom page dimensions', () => {
        const result = buildPDF(makeMinimalParams(), { pageWidth: 612, pageHeight: 792 });
        expect(result).toContain('612.00 792.00');
    });

    it('should accept custom colors', () => {
        const result = buildPDF(makeMinimalParams(), {
            colors: {
                title: '1.000 0.000 0.000',
                credit: '0.000 1.000 0.000',
                debit: '1.000 0.000 0.000',
                text: '0.000 0.000 0.000',
                thBg: '0.900 0.900 0.900',
                thBrd: '0.500 0.500 0.500',
                rowBrd: '0.800 0.800 0.800',
                ptdBg: '0.950 0.950 1.000',
                balBg: '0.900 0.950 1.000',
                balBrd: '0.000 0.000 1.000',
                label: '0.300 0.300 0.300',
                footer: '0.600 0.600 0.600',
            },
        });
        expect(result).toContain('1.000 0.000 0.000 rg');
    });

    it('should accept hex colors', () => {
        const result = buildPDF(makeMinimalParams(), {
            colors: {
                title: '#FF0000',
                credit: '#00FF00',
                debit: '#FF0000',
                text: '#000000',
                thBg: '#E6E6E6',
                thBrd: '#808080',
                rowBrd: '#CCCCCC',
                ptdBg: '#F2F2FF',
                balBg: '#E6F2FF',
                balBrd: '#0000FF',
                label: '#4D4D4D',
                footer: '#999999',
            },
        });
        expect(result).toContain('1 0 0 rg');
    });

    it('should accept tuple colors', () => {
        const result = buildPDF(makeMinimalParams(), {
            colors: {
                title: [255, 0, 0],
                credit: [0, 255, 0],
                debit: [255, 0, 0],
                text: [0, 0, 0],
                thBg: [230, 230, 230],
                thBrd: [128, 128, 128],
                rowBrd: [204, 204, 204],
                ptdBg: [242, 242, 255],
                balBg: [230, 242, 255],
                balBrd: [0, 0, 255],
                label: [77, 77, 77],
                footer: [153, 153, 153],
            },
        });
        expect(result).toContain('1 0 0 rg');
    });
});

describe('buildPDF input validation', () => {
    it('should throw when params is null', () => {
        expect(() => buildPDF(null as unknown as PdfParams)).toThrow('params is required');
    });

    it('should throw when params is undefined', () => {
        expect(() => buildPDF(undefined as unknown as PdfParams)).toThrow('params is required');
    });

    it('should throw when rows is not an array', () => {
        expect(() => buildPDF({ ...makeMinimalParams(), rows: 'not-array' } as unknown as PdfParams)).toThrow('params.rows must be an array');
    });

    it('should throw when headers is not an array', () => {
        expect(() => buildPDF({ ...makeMinimalParams(), headers: null } as unknown as PdfParams)).toThrow('params.headers must be an array');
    });

    it('should throw when row count exceeds safe limit', () => {
        const rows = Array.from({ length: 100_001 }, () => ({
            cells: ['x'], type: 'credit', pointed: false,
        }));
        expect(() => buildPDF(makeMinimalParams({ rows }))).toThrow('exceeds safe limit');
    });

    it('should accept 100,000 rows without throwing', () => {
        const rows = Array.from({ length: 100_000 }, () => ({
            cells: ['x', 'y', 'z'], type: 'credit', pointed: false,
        }));
        // Should not throw (may take a moment)
        const result = buildPDF(makeMinimalParams({ rows }));
        expect(result).toMatch(/^%PDF-1\.4/);
    });
});

describe('buildPDF /Info dictionary', () => {
    it('should contain /Info reference in trailer', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toMatch(/\/Info \d+ 0 R/);
    });

    it('should emit /Producer (pdfnative)', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toContain('/Producer (pdfnative)');
    });

    it('should emit /CreationDate in PDF date format', () => {
        const result = buildPDF(makeMinimalParams());
        expect(result).toMatch(/\/CreationDate \(D:\d{14}\)/);
    });

    it('should emit /Title from visible title when docTitle is absent', () => {
        const result = buildPDF(makeMinimalParams({ title: 'My Report' }));
        expect(result).toContain('/Title (My Report)');
    });

    it('should use docTitle over title when both present', () => {
        const result = buildPDF(makeMinimalParams({ title: 'Visible', docTitle: 'Metadata Title' }));
        expect(result).toContain('/Title (Metadata Title)');
    });

    it('should escape special characters in title', () => {
        const result = buildPDF(makeMinimalParams({ docTitle: 'Report (Q1) 2026\\final' }));
        expect(result).toContain('/Title (Report \\(Q1\\) 2026\\\\final)');
    });

    it('should have valid xref offset for Info object', () => {
        const result = buildPDF(makeMinimalParams());
        // Find the Info object reference in trailer
        const infoMatch = result.match(/\/Info (\d+) 0 R/);
        expect(infoMatch).not.toBeNull();
        const infoObjNum = parseInt(infoMatch![1], 10);
        // Verify the object content
        expect(result).toContain(`${infoObjNum} 0 obj`);
        expect(result).toContain('/Producer (pdfnative)');
    });
});

describe('buildPDF Unicode/CIDFont path', () => {
    function makeUnicodeParams(overrides?: Partial<PdfParams>): PdfParams {
        const fontData = makeMockFontData();
        const fontEntries: FontEntry[] = [{ fontData, fontRef: '/F3', lang: 'test' }];
        return {
            title: 'Unicode Report',
            infoItems: [{ label: 'Period', value: '2026' }],
            balanceText: 'Balance: 100',
            countText: '1 item',
            headers: ['Col A', 'Col B', 'Col C'],
            rows: [
                { cells: ['A', 'B', '10'], type: 'credit', pointed: false },
                { cells: ['B', 'A', '01'], type: 'debit', pointed: true },
            ],
            footerText: 'Footer',
            fontEntries,
            ...overrides,
        };
    }

    it('should produce valid PDF with CIDFont objects', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toMatch(/^%PDF-1\.4/);
        expect(result).toMatch(/%%EOF$/);
        expect(result).toContain('/Subtype /CIDFontType2');
    });

    it('should emit Type0 composite font', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toContain('/Subtype /Type0');
        expect(result).toContain('/Encoding /Identity-H');
    });

    it('should emit FontDescriptor', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toContain('/Type /FontDescriptor');
        expect(result).toContain('/FontFile2');
    });

    it('should emit ToUnicode CMap stream', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toContain('beginbfchar');
        expect(result).toContain('endbfchar');
        expect(result).toContain('endcmap');
    });

    it('should emit /W array in CIDFont', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toMatch(/\/W \[.+\]/);
    });

    it('should include hex-encoded glyph data in content streams', () => {
        const result = buildPDF(makeUnicodeParams());
        // GID 1 for 'A' = hex 0001
        expect(result).toContain('<0001>');
    });

    it('should emit Helvetica fallback fonts alongside CIDFont', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toContain('/BaseFont /Helvetica');
        expect(result).toContain('/BaseFont /Helvetica-Bold');
    });

    it('should have valid xref offsets in Unicode mode', () => {
        const result = buildPDF(makeUnicodeParams());
        const xrefMatch = result.match(/xref\n0 (\d+)\n([\s\S]+?)trailer/);
        expect(xrefMatch).not.toBeNull();
        const entries = xrefMatch![2].trim().split('\n');
        expect(entries[0]).toMatch(/0000000000 65535 f/);
        for (let i = 1; i < entries.length; i++) {
            const offsetMatch = entries[i].match(/^(\d{10}) 00000 n/);
            expect(offsetMatch).not.toBeNull();
            const offset = parseInt(offsetMatch![1], 10);
            expect(result.substring(offset, offset + `${i} 0 obj`.length)).toBe(`${i} 0 obj`);
        }
    });

    it('should handle pagination in Unicode mode', () => {
        const rows = Array.from({ length: 80 }, (_, i) => ({
            cells: ['A', 'B', `${i}`],
            type: 'credit',
            pointed: false,
        }));
        const result = buildPDF(makeUnicodeParams({ rows }));
        const pageCount = (result.match(/\/Type \/Page /g) || []).length;
        expect(pageCount).toBeGreaterThan(1);
    });

    it('should emit /Info dictionary in Unicode mode', () => {
        const result = buildPDF(makeUnicodeParams());
        expect(result).toContain('/Producer (pdfnative)');
        expect(result).toMatch(/\/Info \d+ 0 R/);
    });

    it('should support fontData shorthand (single font)', () => {
        const fontData = makeMockFontData();
        const result = buildPDF(makeMinimalParams({ fontData }));
        expect(result).toContain('/Subtype /CIDFontType2');
        expect(result).toContain('/Encoding /Identity-H');
    });

    // ── PDF/A-3 with attachments ─────────────────────────────────
    it('should produce PDF/A-3b with embedded file attachments', () => {
        const xmlData = new TextEncoder().encode('<invoice><total>100</total></invoice>');
        const result = buildPDF(makeMinimalParams(), {
            tagged: 'pdfa3b',
            attachments: [{
                filename: 'invoice.xml',
                data: xmlData,
                mimeType: 'application/xml',
                relationship: 'Data',
            }],
        });
        expect(result).toContain('%PDF-1.7');
        expect(result).toContain('pdfaid:part>3');
        expect(result).toContain('/AF [');
        expect(result).toContain('/EmbeddedFiles');
        expect(result).toContain('/AFRelationship /Data');
        expect(result).toContain('/Type /Filespec');
        expect(result).toContain('/Type /EmbeddedFile');
        expect(result).toContain('(invoice.xml)');
    });

    it('should produce PDF/A-3b without attachments', () => {
        const result = buildPDF(makeMinimalParams(), { tagged: 'pdfa3b' });
        expect(result).toContain('%PDF-1.7');
        expect(result).toContain('pdfaid:part>3');
        expect(result).not.toContain('/AF [');
    });

    it('should throw when attachments used without pdfa3b', () => {
        const att = [{
            filename: 'test.xml',
            data: new TextEncoder().encode('<x/>'),
            mimeType: 'application/xml',
        }];
        expect(() => buildPDF(makeMinimalParams(), { tagged: true, attachments: att })).toThrow('pdfa3b');
        expect(() => buildPDF(makeMinimalParams(), { attachments: att })).toThrow('pdfa3b');
    });
});
