import { describe, it, expect } from 'vitest';
import { validateWatermark, buildWatermarkState } from '../../src/core/pdf-watermark.js';
import { buildPDF } from '../../src/core/pdf-builder.js';
import { buildDocumentPDF } from '../../src/core/pdf-document.js';
import type { PdfParams, WatermarkOptions, EncodingContext } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';
import { createEncodingContext } from '../../src/core/encoding-context.js';

// ── Helpers ──────────────────────────────────────────────────────────

function makeEnc(): EncodingContext {
    return createEncodingContext([]);
}

function makeMinimalJPEG(): Uint8Array {
    const bytes = [
        0xFF, 0xD8,
        0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00,
        0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00,
        0xFF, 0xDB, 0x00, 0x43, 0x00,
        0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07,
        0x07, 0x07, 0x09, 0x09, 0x08, 0x0A, 0x0C, 0x14,
        0x0D, 0x0C, 0x0B, 0x0B, 0x0C, 0x19, 0x12, 0x13,
        0x0F, 0x14, 0x1D, 0x1A, 0x1F, 0x1E, 0x1D, 0x1A,
        0x1C, 0x1C, 0x20, 0x24, 0x2E, 0x27, 0x20, 0x22,
        0x2C, 0x23, 0x1C, 0x1C, 0x28, 0x37, 0x29, 0x2C,
        0x30, 0x31, 0x34, 0x34, 0x34, 0x1F, 0x27, 0x39,
        0x3D, 0x38, 0x32, 0x3C, 0x2E, 0x33, 0x34, 0x32,
        0xFF, 0xC0, 0x00, 0x11, 0x08,
        0x00, 0x02, 0x00, 0x02,
        0x03, 0x01, 0x11, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11, 0x01,
        0xFF, 0xC4, 0x00, 0x1F, 0x00,
        0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B,
        0xFF, 0xDA, 0x00, 0x0C, 0x03,
        0x01, 0x00, 0x02, 0x11, 0x03, 0x11,
        0x00, 0x3F, 0x00,
        0x00, 0x00, 0x00, 0x00,
        0xFF, 0xD9,
    ];
    return new Uint8Array(bytes);
}

function makeBuilderParams(overrides?: Partial<PdfParams>): PdfParams {
    return {
        title: 'Test Report',
        infoItems: [{ label: 'Period', value: 'Jan 2026' }],
        balanceText: 'Balance: $100.00',
        countText: '2 items',
        headers: ['Date', 'Description', 'Amount'],
        rows: [
            { cells: ['01/01', 'Item A', '$50.00'], type: 'credit', pointed: false },
            { cells: ['01/02', 'Item B', '-$25.00'], type: 'debit', pointed: true },
        ],
        footerText: 'Generated by pdfnative',
        ...overrides,
    };
}

function makeDocParams(overrides?: Partial<DocumentParams>): DocumentParams {
    return {
        title: 'Test Document',
        blocks: [
            { type: 'paragraph', text: 'Hello world' },
        ],
        ...overrides,
    };
}

// ── validateWatermark ────────────────────────────────────────────────

describe('validateWatermark', () => {
    it('should not throw for non-PDF/A modes', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 0.1 } };
        expect(() => validateWatermark(wm, false)).not.toThrow();
        expect(() => validateWatermark(wm, true)).not.toThrow();
        expect(() => validateWatermark(wm, 'pdfa2b')).not.toThrow();
    });

    it('should throw for PDF/A-1b with text opacity < 1.0', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 0.5 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should throw for PDF/A-1b with image opacity < 1.0', () => {
        const wm: WatermarkOptions = { image: { data: new Uint8Array([]), opacity: 0.3 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should throw for PDF/A-1b with default text opacity (0.15 < 1.0)', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should not throw for PDF/A-1b with opacity = 1.0', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 1.0 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).not.toThrow();
    });
});

// ── buildWatermarkState ──────────────────────────────────────────────

describe('buildWatermarkState', () => {
    it('should build text watermark ops', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(1);
        expect(state.backgroundOps).toContain('gs');
        expect(state.backgroundOps).toContain('BT');
        expect(state.backgroundOps).toContain('Tm');
        expect(state.backgroundOps).toContain('DRAFT');
        expect(state.foregroundOps).toBe('');
        expect(state.imageXObj).toBeNull();
    });

    it('should build image watermark ops', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { image: { data: makeMinimalJPEG() } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(1);
        expect(state.backgroundOps).toContain('gs');
        expect(state.backgroundOps).toContain('/ImW1 Do');
        expect(state.imageXObj).not.toBeNull();
        expect(state.parsedImage).not.toBeNull();
    });

    it('should build both text and image watermark', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'CONFIDENTIAL' },
            image: { data: makeMinimalJPEG() },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(2);
        expect(state.backgroundOps).toContain('CONFIDENTIAL');
        expect(state.backgroundOps).toContain('/ImW1 Do');
    });

    it('should place ops in foreground when position is foreground', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT' },
            position: 'foreground',
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.backgroundOps).toBe('');
        expect(state.foregroundOps).toContain('DRAFT');
    });

    it('should use custom color and font size', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', color: '#ff0000', fontSize: 80 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.backgroundOps).toContain('1 0 0 rg');
        expect(state.backgroundOps).toContain('80.00 Tf');
    });

    it('should use custom opacity', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', opacity: 0.5 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        const gsValues = [...state.extGStates.values()];
        expect(gsValues[0]).toContain('/ca 0.5');
    });

    it('should include rotation matrix in text watermark', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', angle: -45 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // cos(-45°) ≈ 0.71, sin(-45°) ≈ -0.71 (fmtNum rounds to 2dp)
        expect(state.backgroundOps).toMatch(/0\.71 -0\.71 0\.71 0\.71.*Tm/);
    });

    it('should handle angle = 0 (no rotation)', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', angle: 0 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // cos(0) = 1, sin(0) = 0
        expect(state.backgroundOps).toMatch(/1\.00 0\.00 0\.00 1\.00/);
    });

    it('should center image on page with custom dimensions', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            image: { data: makeMinimalJPEG(), width: 200, height: 100 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // Center: x=(595-200)/2=197.5, y=(842-100)/2=371
        expect(state.backgroundOps).toContain('200');
        expect(state.backgroundOps).toContain('100');
    });

    it('should produce valid ExtGState dict', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { text: { text: 'TEST', opacity: 0.25 } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        const gsValues = [...state.extGStates.values()];
        expect(gsValues[0]).toBe('<< /Type /ExtGState /ca 0.25 >>');
    });
});

// ── Integration: buildPDF with watermark ─────────────────────────────

describe('buildPDF watermark integration', () => {
    it('should produce valid PDF with text watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ExtGState');
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with foreground watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' }, position: 'foreground' },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with image watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { image: { data: makeMinimalJPEG() } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ImW1');
        expect(result).toContain('/ExtGState');
    });

    it('should produce valid PDF with text + image watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: {
                text: { text: 'CONFIDENTIAL' },
                image: { data: makeMinimalJPEG() },
            },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('CONFIDENTIAL');
        expect(result).toContain('/ImW1');
    });

    it('should include ExtGState in page resources', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('/ExtGState <<');
        expect(result).toContain('/GS1');
    });

    it('watermark on every page of multi-page PDF', () => {
        const manyRows = Array.from({ length: 100 }, (_, i) => ({
            cells: [`${i}`, `Item ${i}`, `$${i}.00`],
            type: 'credit' as const,
            pointed: false,
        }));
        const result = buildPDF(makeBuilderParams({ rows: manyRows }), {
            watermark: { text: { text: 'DRAFT' } },
        });
        // Count DRAFT occurrences — should be at least 2 pages worth
        const draftCount = (result.match(/DRAFT/g) || []).length;
        expect(draftCount).toBeGreaterThanOrEqual(2);
    });

    it('should throw for PDF/A-1b with transparency', () => {
        expect(() => buildPDF(makeBuilderParams(), {
            tagged: 'pdfa1b',
            watermark: { text: { text: 'DRAFT' } },
        })).toThrow('PDF/A-1b');
    });
});

// ── Integration: buildDocumentPDF with watermark ─────────────────────

describe('buildDocumentPDF watermark integration', () => {
    it('should produce valid PDF with text watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ExtGState');
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with foreground watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'SAMPLE' }, position: 'foreground' },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('SAMPLE');
    });

    it('should produce valid PDF with image watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { image: { data: makeMinimalJPEG() } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ImW1');
        expect(result).toContain('/ExtGState');
    });

    it('should include ExtGState in page resources', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('/ExtGState <<');
        expect(result).toContain('/GS1');
    });

    // Regression: watermark must not cause object number collisions (xref corruption)
    it('should have no duplicate object numbers with text watermark (builder)', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT', fontSize: 60, opacity: 0.15 }, position: 'background' },
        });
        const objNums = [...result.matchAll(/^(\d+) 0 obj\b/gm)].map(m => Number(m[1]));
        const unique = new Set(objNums);
        expect(objNums.length).toBe(unique.size);
    });

    it('should have no duplicate object numbers with image watermark (builder)', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { image: { data: makeMinimalJPEG(), opacity: 0.08 }, position: 'background' },
        });
        const objNums = [...result.matchAll(/^(\d+) 0 obj\b/gm)].map(m => Number(m[1]));
        const unique = new Set(objNums);
        expect(objNums.length).toBe(unique.size);
    });

    it('watermark on every page of multi-page document', () => {
        const blocks = Array.from({ length: 50 }, () => ({
            type: 'paragraph' as const,
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '.repeat(5),
        }));
        const result = buildDocumentPDF(makeDocParams({ blocks }), {
            watermark: { text: { text: 'DRAFT' } },
        });
        const draftCount = (result.match(/DRAFT/g) || []).length;
        expect(draftCount).toBeGreaterThanOrEqual(2);
    });

    it('should throw for PDF/A-1b with transparency', () => {
        expect(() => buildDocumentPDF(makeDocParams(), {
            tagged: 'pdfa1b',
            watermark: { text: { text: 'DRAFT' } },
        })).toThrow('PDF/A-1b');
    });

    it('should produce valid PDF with tagged mode + watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            tagged: true,
            watermark: { text: { text: 'DRAFT', opacity: 1.0 } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('DRAFT');
        // Watermark should NOT be in structure tree (not accessible content)
    });

    it('should properly end with %%EOF', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('%%EOF');
    });

    it('should produce valid PDF with combined header/footer + watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            headerTemplate: { center: 'Company Inc.' },
            footerTemplate: { left: 'Confidential', right: '{page}/{pages}' },
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('Company Inc.');
        expect(result).toContain('DRAFT');
        expect(result).toContain('Confidential');
    });
});

// ── Regression: centering & encoding (v1.0.5) ────────────────────────
//
// These tests guard against three regressions discovered in v1.0.4:
//   1. Vertical centering used `-fontSize/2` as the baseline offset.
//      The actual visual center of caps text sits at capHeight/2 ≈ 0.36×
//      fontSize above the baseline, so the watermark drifted downward by
//      ~14% of the font size. Combined with rotation this pushed the
//      visual centre well off the page centre.
//   2. The text was encoded with `pdfString()` (WinAnsi) regardless of
//      the active encoding context. In Unicode/CIDFont mode this produced
//      garbage glyphs and wrong widths.
//   3. Width measurement (`enc.tw()`) and rendering (`enc.f2`) used
//      consistent fonts, but the text-encoding helpers did not. Centering
//      now derives `offsetY` from the font's actual cap-height when the
//      encoding context exposes metrics.

describe('text watermark centering (regression)', () => {
    /**
     * Extract the `Tm` (text matrix) operator coefficients from a
     * watermark op string. The matrix layout is `a b c d e f Tm` where
     * (e, f) is the translation (tx, ty).
     */
    function parseTm(ops: string): { a: number; b: number; c: number; d: number; tx: number; ty: number } {
        const m = ops.match(/(-?\d+\.\d+) (-?\d+\.\d+) (-?\d+\.\d+) (-?\d+\.\d+) (-?\d+\.\d+) (-?\d+\.\d+) Tm/);
        if (!m) throw new Error('Tm operator not found in watermark ops');
        return {
            a: Number(m[1]),
            b: Number(m[2]),
            c: Number(m[3]),
            d: Number(m[4]),
            tx: Number(m[5]),
            ty: Number(m[6]),
        };
    }

    it('vertical offset uses cap-height/2, not fontSize/2 (Latin mode)', () => {
        const enc = makeEnc();
        const pgW = 595;
        const pgH = 842;
        // Use angle = 0 so the rotation does not mix offsetX and offsetY:
        // tx = cx + offsetX, ty = cy + offsetY (cleanly observable).
        const wm: WatermarkOptions = { text: { text: 'CONFIDENTIAL', angle: 0, fontSize: 60 } };
        const state = buildWatermarkState(wm, pgW, pgH, enc);
        const { ty } = parseTm(state.backgroundOps);

        // Helvetica cap height = 0.718 × fontSize, so offsetY = -0.359 × 60 ≈ -21.54
        // Expected ty = pgH/2 + offsetY = 421 - 21.54 ≈ 399.46
        const expectedTy = pgH / 2 - (60 * 0.718) / 2;
        expect(ty).toBeCloseTo(expectedTy, 1);

        // The previous (buggy) value would have been pgH/2 - 60/2 = 391.
        // Assert we are not at the old position (strictly higher on the page).
        expect(ty).toBeGreaterThan(pgH / 2 - 60 / 2 + 5);
    });

    it('horizontal offset re-centers the text width on the page', () => {
        const enc = makeEnc();
        const pgW = 595;
        const pgH = 842;
        const wm: WatermarkOptions = { text: { text: 'DRAFT', angle: 0, fontSize: 40 } };
        const state = buildWatermarkState(wm, pgW, pgH, enc);
        const { tx } = parseTm(state.backgroundOps);
        // For angle=0: tx = cx - textWidth/2. We accept any positive width;
        // tx must be strictly less than the page centre and strictly
        // greater than zero.
        expect(tx).toBeLessThan(pgW / 2);
        expect(tx).toBeGreaterThan(0);
    });

    it('Latin watermark text is encoded as WinAnsi literal (round parens)', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        const state = buildWatermarkState(wm, 595, 842, enc);
        // WinAnsi literal form: (DRAFT) Tj — must NOT be hex form <...>.
        expect(state.backgroundOps).toContain('(DRAFT) Tj');
        expect(state.backgroundOps).not.toMatch(/<[0-9A-F]+> Tj/);
    });

    it('Unicode/CIDFont mode encodes watermark as 2-byte GID hex', async () => {
        // Load a CIDFont (Cyrillic data ships pre-built and is small).
        const cyrModule = await import('../../fonts/noto-cyrillic-data.js');
        const fontData = {
            metrics: cyrModule.metrics,
            fontName: cyrModule.fontName,
            cmap: cyrModule.cmap,
            defaultWidth: cyrModule.defaultWidth,
            widths: cyrModule.widths,
            pdfWidthArray: cyrModule.pdfWidthArray,
            ttfBase64: cyrModule.ttfBase64,
            gsub: cyrModule.gsub,
            ligatures: cyrModule.ligatures,
            markAnchors: cyrModule.markAnchors as never,
            mark2mark: cyrModule.mark2mark as never,
        };
        const fontEntry = { fontData, fontRef: '/F2', lang: 'cyr' };
        const enc = createEncodingContext([fontEntry]);

        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // CIDFont mode emits hex GID strings <XXXX...> not WinAnsi (...).
        expect(state.backgroundOps).toMatch(/<[0-9A-F]+> Tj/);
        expect(state.backgroundOps).not.toContain('(DRAFT)');
        // Hex string should have one 4-digit GID per character (5 chars × 4 = 20 hex digits).
        const hexMatch = state.backgroundOps.match(/<([0-9A-F]+)> Tj/);
        expect(hexMatch).not.toBeNull();
        expect(hexMatch![1].length).toBe('DRAFT'.length * 4);
    });

    it('Unicode mode uses font cap-height metrics for vertical centering', async () => {
        const cyrModule = await import('../../fonts/noto-cyrillic-data.js');
        const fontData = {
            metrics: cyrModule.metrics,
            fontName: cyrModule.fontName,
            cmap: cyrModule.cmap,
            defaultWidth: cyrModule.defaultWidth,
            widths: cyrModule.widths,
            pdfWidthArray: cyrModule.pdfWidthArray,
            ttfBase64: cyrModule.ttfBase64,
            gsub: cyrModule.gsub,
            ligatures: cyrModule.ligatures,
            markAnchors: cyrModule.markAnchors as never,
            mark2mark: cyrModule.mark2mark as never,
        };
        const fontEntry = { fontData, fontRef: '/F2', lang: 'cyr' };
        const enc = createEncodingContext([fontEntry]);
        const pgH = 842;
        const wm: WatermarkOptions = { text: { text: 'DRAFT', angle: 0, fontSize: 60 } };
        const state = buildWatermarkState(wm, 595, pgH, enc);
        const { ty } = parseTm(state.backgroundOps);

        const expectedRatio = fontData.metrics.capHeight / fontData.metrics.unitsPerEm;
        const expectedTy = pgH / 2 - (60 * expectedRatio) / 2;
        expect(ty).toBeCloseTo(expectedTy, 1);
    });

    it('rotation preserves visual centering of the text bounding box', () => {
        const enc = makeEnc();
        const pgW = 595;
        const pgH = 842;
        const wm: WatermarkOptions = { text: { text: 'CONFIDENTIAL', angle: 45, fontSize: 60 } };
        const state = buildWatermarkState(wm, pgW, pgH, enc);
        const { a, b, c, d, tx, ty } = parseTm(state.backgroundOps);

        // The four corners of the text bounding box (local coordinates):
        // baseline-start (0, 0), baseline-end (textWidth, 0),
        // top-start (0, capHeight), top-end (textWidth, capHeight).
        // After applying the Tm matrix [a b; c d; tx ty]:
        //   global = local · M + (tx, ty)
        // The midpoint of the bounding box must equal page centre.
        const sz = 60;
        const capHeight = sz * 0.718; // Helvetica default
        // Recompute the textWidth via the same encoder path the renderer used:
        // because we do not have a direct accessor we re-derive it from
        // the matrix: tx, ty are placed at (cx + offsetX·cos − offsetY·sin,
        // cy + offsetX·sin + offsetY·cos). With offsetY = −capHeight/2
        // we can solve for offsetX and verify centering.
        const cos = a;
        const sin = b;
        // c = -sin, d = cos
        expect(c).toBeCloseTo(-sin, 2);
        expect(d).toBeCloseTo(cos, 2);
        const offsetY = -capHeight / 2;
        // From: tx = cx + offsetX·cos − offsetY·sin
        const offsetX = (tx - pgW / 2 + offsetY * sin) / cos;
        // The visual center of the bounding box is at local (textWidth/2, capHeight/2).
        // For correct centering this must map to (cx, cy):
        //   cx = tx + (textWidth/2)·a + (capHeight/2)·c
        //   cy = ty + (textWidth/2)·b + (capHeight/2)·d
        // textWidth = -2·offsetX (since offsetX = -textWidth/2):
        const textWidth = -2 * offsetX;
        const visualCx = tx + (textWidth / 2) * a + (capHeight / 2) * c;
        const visualCy = ty + (textWidth / 2) * b + (capHeight / 2) * d;
        // Precision 0 ⇒ within 0.5pt. The watermark renderer formats Tm
        // coefficients with 2 decimals (`fmtNum`), so chaining rotation +
        // rounding accumulates ~0.1pt error — well within the half-point
        // tolerance that PDF rendering anyway snaps to.
        expect(visualCx).toBeCloseTo(pgW / 2, 0);
        expect(visualCy).toBeCloseTo(pgH / 2, 0);
    });
});
