import { describe, it, expect } from 'vitest';
import { validateWatermark, buildWatermarkState } from '../../src/core/pdf-watermark.js';
import { buildPDF } from '../../src/core/pdf-builder.js';
import { buildDocumentPDF } from '../../src/core/pdf-document.js';
import type { PdfParams, WatermarkOptions, EncodingContext } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';
import { createEncodingContext } from '../../src/core/encoding-context.js';

// ── Helpers ──────────────────────────────────────────────────────────

function makeEnc(): EncodingContext {
    return createEncodingContext([]);
}

function makeMinimalJPEG(): Uint8Array {
    const bytes = [
        0xFF, 0xD8,
        0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00,
        0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00,
        0xFF, 0xDB, 0x00, 0x43, 0x00,
        0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07,
        0x07, 0x07, 0x09, 0x09, 0x08, 0x0A, 0x0C, 0x14,
        0x0D, 0x0C, 0x0B, 0x0B, 0x0C, 0x19, 0x12, 0x13,
        0x0F, 0x14, 0x1D, 0x1A, 0x1F, 0x1E, 0x1D, 0x1A,
        0x1C, 0x1C, 0x20, 0x24, 0x2E, 0x27, 0x20, 0x22,
        0x2C, 0x23, 0x1C, 0x1C, 0x28, 0x37, 0x29, 0x2C,
        0x30, 0x31, 0x34, 0x34, 0x34, 0x1F, 0x27, 0x39,
        0x3D, 0x38, 0x32, 0x3C, 0x2E, 0x33, 0x34, 0x32,
        0xFF, 0xC0, 0x00, 0x11, 0x08,
        0x00, 0x02, 0x00, 0x02,
        0x03, 0x01, 0x11, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11, 0x01,
        0xFF, 0xC4, 0x00, 0x1F, 0x00,
        0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0A, 0x0B,
        0xFF, 0xDA, 0x00, 0x0C, 0x03,
        0x01, 0x00, 0x02, 0x11, 0x03, 0x11,
        0x00, 0x3F, 0x00,
        0x00, 0x00, 0x00, 0x00,
        0xFF, 0xD9,
    ];
    return new Uint8Array(bytes);
}

function makeBuilderParams(overrides?: Partial<PdfParams>): PdfParams {
    return {
        title: 'Test Report',
        infoItems: [{ label: 'Period', value: 'Jan 2026' }],
        balanceText: 'Balance: $100.00',
        countText: '2 items',
        headers: ['Date', 'Description', 'Amount'],
        rows: [
            { cells: ['01/01', 'Item A', '$50.00'], type: 'credit', pointed: false },
            { cells: ['01/02', 'Item B', '-$25.00'], type: 'debit', pointed: true },
        ],
        footerText: 'Generated by pdfnative',
        ...overrides,
    };
}

function makeDocParams(overrides?: Partial<DocumentParams>): DocumentParams {
    return {
        title: 'Test Document',
        blocks: [
            { type: 'paragraph', text: 'Hello world' },
        ],
        ...overrides,
    };
}

// ── validateWatermark ────────────────────────────────────────────────

describe('validateWatermark', () => {
    it('should not throw for non-PDF/A modes', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 0.1 } };
        expect(() => validateWatermark(wm, false)).not.toThrow();
        expect(() => validateWatermark(wm, true)).not.toThrow();
        expect(() => validateWatermark(wm, 'pdfa2b')).not.toThrow();
    });

    it('should throw for PDF/A-1b with text opacity < 1.0', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 0.5 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should throw for PDF/A-1b with image opacity < 1.0', () => {
        const wm: WatermarkOptions = { image: { data: new Uint8Array([]), opacity: 0.3 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should throw for PDF/A-1b with default text opacity (0.15 < 1.0)', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        expect(() => validateWatermark(wm, 'pdfa1b')).toThrow('PDF/A-1b');
    });

    it('should not throw for PDF/A-1b with opacity = 1.0', () => {
        const wm: WatermarkOptions = { text: { text: 'DRAFT', opacity: 1.0 } };
        expect(() => validateWatermark(wm, 'pdfa1b')).not.toThrow();
    });
});

// ── buildWatermarkState ──────────────────────────────────────────────

describe('buildWatermarkState', () => {
    it('should build text watermark ops', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { text: { text: 'DRAFT' } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(1);
        expect(state.backgroundOps).toContain('gs');
        expect(state.backgroundOps).toContain('BT');
        expect(state.backgroundOps).toContain('Tm');
        expect(state.backgroundOps).toContain('DRAFT');
        expect(state.foregroundOps).toBe('');
        expect(state.imageXObj).toBeNull();
    });

    it('should build image watermark ops', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { image: { data: makeMinimalJPEG() } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(1);
        expect(state.backgroundOps).toContain('gs');
        expect(state.backgroundOps).toContain('/ImW1 Do');
        expect(state.imageXObj).not.toBeNull();
        expect(state.parsedImage).not.toBeNull();
    });

    it('should build both text and image watermark', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'CONFIDENTIAL' },
            image: { data: makeMinimalJPEG() },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.extGStates.size).toBe(2);
        expect(state.backgroundOps).toContain('CONFIDENTIAL');
        expect(state.backgroundOps).toContain('/ImW1 Do');
    });

    it('should place ops in foreground when position is foreground', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT' },
            position: 'foreground',
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.backgroundOps).toBe('');
        expect(state.foregroundOps).toContain('DRAFT');
    });

    it('should use custom color and font size', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', color: '#ff0000', fontSize: 80 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        expect(state.backgroundOps).toContain('1 0 0 rg');
        expect(state.backgroundOps).toContain('80.00 Tf');
    });

    it('should use custom opacity', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', opacity: 0.5 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        const gsValues = [...state.extGStates.values()];
        expect(gsValues[0]).toContain('/ca 0.5');
    });

    it('should include rotation matrix in text watermark', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', angle: -45 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // cos(-45°) ≈ 0.71, sin(-45°) ≈ -0.71 (fmtNum rounds to 2dp)
        expect(state.backgroundOps).toMatch(/0\.71 -0\.71 0\.71 0\.71.*Tm/);
    });

    it('should handle angle = 0 (no rotation)', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            text: { text: 'DRAFT', angle: 0 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // cos(0) = 1, sin(0) = 0
        expect(state.backgroundOps).toMatch(/1\.00 0\.00 0\.00 1\.00/);
    });

    it('should center image on page with custom dimensions', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = {
            image: { data: makeMinimalJPEG(), width: 200, height: 100 },
        };
        const state = buildWatermarkState(wm, 595, 842, enc);

        // Center: x=(595-200)/2=197.5, y=(842-100)/2=371
        expect(state.backgroundOps).toContain('200');
        expect(state.backgroundOps).toContain('100');
    });

    it('should produce valid ExtGState dict', () => {
        const enc = makeEnc();
        const wm: WatermarkOptions = { text: { text: 'TEST', opacity: 0.25 } };
        const state = buildWatermarkState(wm, 595, 842, enc);

        const gsValues = [...state.extGStates.values()];
        expect(gsValues[0]).toBe('<< /Type /ExtGState /ca 0.25 >>');
    });
});

// ── Integration: buildPDF with watermark ─────────────────────────────

describe('buildPDF watermark integration', () => {
    it('should produce valid PDF with text watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ExtGState');
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with foreground watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' }, position: 'foreground' },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with image watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { image: { data: makeMinimalJPEG() } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ImW1');
        expect(result).toContain('/ExtGState');
    });

    it('should produce valid PDF with text + image watermark', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: {
                text: { text: 'CONFIDENTIAL' },
                image: { data: makeMinimalJPEG() },
            },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('CONFIDENTIAL');
        expect(result).toContain('/ImW1');
    });

    it('should include ExtGState in page resources', () => {
        const result = buildPDF(makeBuilderParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('/ExtGState <<');
        expect(result).toContain('/GS1');
    });

    it('watermark on every page of multi-page PDF', () => {
        const manyRows = Array.from({ length: 100 }, (_, i) => ({
            cells: [`${i}`, `Item ${i}`, `$${i}.00`],
            type: 'credit' as const,
            pointed: false,
        }));
        const result = buildPDF(makeBuilderParams({ rows: manyRows }), {
            watermark: { text: { text: 'DRAFT' } },
        });
        // Count DRAFT occurrences — should be at least 2 pages worth
        const draftCount = (result.match(/DRAFT/g) || []).length;
        expect(draftCount).toBeGreaterThanOrEqual(2);
    });

    it('should throw for PDF/A-1b with transparency', () => {
        expect(() => buildPDF(makeBuilderParams(), {
            tagged: 'pdfa1b',
            watermark: { text: { text: 'DRAFT' } },
        })).toThrow('PDF/A-1b');
    });
});

// ── Integration: buildDocumentPDF with watermark ─────────────────────

describe('buildDocumentPDF watermark integration', () => {
    it('should produce valid PDF with text watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ExtGState');
        expect(result).toContain('DRAFT');
    });

    it('should produce valid PDF with foreground watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'SAMPLE' }, position: 'foreground' },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('SAMPLE');
    });

    it('should produce valid PDF with image watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { image: { data: makeMinimalJPEG() } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('/ImW1');
        expect(result).toContain('/ExtGState');
    });

    it('should include ExtGState in page resources', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('/ExtGState <<');
        expect(result).toContain('/GS1');
    });

    it('watermark on every page of multi-page document', () => {
        const blocks = Array.from({ length: 50 }, () => ({
            type: 'paragraph' as const,
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '.repeat(5),
        }));
        const result = buildDocumentPDF(makeDocParams({ blocks }), {
            watermark: { text: { text: 'DRAFT' } },
        });
        const draftCount = (result.match(/DRAFT/g) || []).length;
        expect(draftCount).toBeGreaterThanOrEqual(2);
    });

    it('should throw for PDF/A-1b with transparency', () => {
        expect(() => buildDocumentPDF(makeDocParams(), {
            tagged: 'pdfa1b',
            watermark: { text: { text: 'DRAFT' } },
        })).toThrow('PDF/A-1b');
    });

    it('should produce valid PDF with tagged mode + watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            tagged: true,
            watermark: { text: { text: 'DRAFT', opacity: 1.0 } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('DRAFT');
        // Watermark should NOT be in structure tree (not accessible content)
    });

    it('should properly end with %%EOF', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toContain('%%EOF');
    });

    it('should produce valid PDF with combined header/footer + watermark', () => {
        const result = buildDocumentPDF(makeDocParams(), {
            headerTemplate: { center: 'Company Inc.' },
            footerTemplate: { left: 'Confidential', right: '{page}/{pages}' },
            watermark: { text: { text: 'DRAFT' } },
        });
        expect(result).toMatch(/^%PDF-/);
        expect(result).toContain('Company Inc.');
        expect(result).toContain('DRAFT');
        expect(result).toContain('Confidential');
    });
});
