import { describe, it, expect, afterEach } from 'vitest';
import {
    buildDocumentPDFBytes,
    buildPDFBytes,
    setDefaultCreationDate,
    getDefaultCreationDate,
} from '../../src/index.js';
import { buildPdfMetadata } from '../../src/core/pdf-tags.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';
import type { PdfParams } from '../../src/types/pdf-types.js';

// v1.8.0 — process-wide default creation instant for reproducible builds.

const PINNED = new Date('2026-01-01T00:00:00Z');
const OTHER = new Date('2019-07-14T12:34:56Z');

function doc(): DocumentParams {
    return {
        title: 'Reproducible',
        blocks: [
            { type: 'heading', level: 1, text: 'Intro' },
            { type: 'paragraph', text: 'Deterministic output.' },
        ],
    };
}

function table(): PdfParams {
    return {
        title: 'Reproducible table',
        infoItems: [{ label: 'Period', value: 'Jan 2026' }],
        balanceText: 'Balance: 100.00',
        countText: '1 item',
        headers: ['Label', 'Value'],
        rows: [{ cells: ['a', '1'], type: 'credit', pointed: false }],
        footerText: 'Generated by pdfnative',
    };
}

function latin1(bytes: Uint8Array): string {
    return new TextDecoder('latin1').decode(bytes);
}

afterEach(() => {
    setDefaultCreationDate(null);
});

// v1.8.0 — dates are written in UTC whatever the host zone, so a pinned
// instant yields the same bytes on every machine (the last host-dependent
// input to a pinned build until then).
describe('time-zone independence', () => {
    const savedTz = process.env.TZ;
    afterEach(() => { process.env.TZ = savedTz; });

    /** Run `fn` under a host time zone; Node re-reads TZ on assignment. */
    function underTz<T>(tz: string, fn: () => T): T {
        process.env.TZ = tz;
        try { return fn(); } finally { process.env.TZ = savedTz; }
    }

    it('formats /CreationDate and the XMP dates in UTC under any host zone', () => {
        const at = new Date('2026-01-01T12:00:00Z');
        for (const tz of ['Pacific/Auckland', 'America/Los_Angeles', 'UTC']) {
            const { pdfDate, xmpDate } = underTz(tz, () => buildPdfMetadata(at));
            expect(pdfDate).toBe("D:20260101120000+00'00'");
            expect(xmpDate).toBe('2026-01-01T12:00:00+00:00');
        }
    });

    it('builds byte-identical documents from one pinned instant under two zones', () => {
        const a = underTz('America/Los_Angeles', () => buildDocumentPDFBytes(doc(), { creationDate: PINNED }));
        const b = underTz('Asia/Tokyo', () => buildDocumentPDFBytes(doc(), { creationDate: PINNED }));
        expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
        const t1 = underTz('America/Los_Angeles', () => buildPDFBytes(table(), { creationDate: PINNED }));
        const t2 = underTz('Asia/Tokyo', () => buildPDFBytes(table(), { creationDate: PINNED }));
        expect(Buffer.from(t1).equals(Buffer.from(t2))).toBe(true);
    });

    it('renders the {date} placeholder on the UTC day of the pinned instant', () => {
        // 02:00Z on 1 January is still 31 December in Los Angeles.
        const bytes = underTz('America/Los_Angeles', () => buildDocumentPDFBytes(
            { ...doc(), footerText: 'Built {date}' },
            { creationDate: new Date('2026-01-01T02:00:00Z') },
        ));
        const text = latin1(bytes);
        expect(text).toContain('2026-01-01');
        expect(text).not.toContain('2025-12-31');
    });
});

describe('setDefaultCreationDate', () => {
    it('is unset by default', () => {
        expect(getDefaultCreationDate()).toBeNull();
    });

    it('round-trips through the getter and clears with null', () => {
        setDefaultCreationDate(PINNED);
        expect(getDefaultCreationDate()).toBe(PINNED);
        setDefaultCreationDate(null);
        expect(getDefaultCreationDate()).toBeNull();
    });

    it('rejects a non-Date and an invalid Date', () => {
        expect(() => setDefaultCreationDate('2026-01-01' as unknown as Date)).toThrow(/valid Date or null/);
        expect(() => setDefaultCreationDate(new Date('nope'))).toThrow(/valid Date or null/);
    });

    it('makes repeated document builds byte-identical', () => {
        setDefaultCreationDate(PINNED);
        const a = buildDocumentPDFBytes(doc());
        const b = buildDocumentPDFBytes(doc());
        expect(Buffer.from(b).equals(Buffer.from(a))).toBe(true);
    });

    it('makes repeated table builds byte-identical', () => {
        setDefaultCreationDate(PINNED);
        const a = buildPDFBytes(table());
        const b = buildPDFBytes(table());
        expect(Buffer.from(b).equals(Buffer.from(a))).toBe(true);
    });

    it('is equivalent to passing layout.creationDate explicitly', () => {
        const explicit = buildDocumentPDFBytes(doc(), { creationDate: PINNED });
        setDefaultCreationDate(PINNED);
        const viaDefault = buildDocumentPDFBytes(doc());
        expect(Buffer.from(viaDefault).equals(Buffer.from(explicit))).toBe(true);
    });

    it('yields to an explicit layout.creationDate', () => {
        setDefaultCreationDate(PINNED);
        const pinned = buildDocumentPDFBytes(doc());
        const overridden = buildDocumentPDFBytes(doc(), { creationDate: OTHER });
        expect(Buffer.from(overridden).equals(Buffer.from(pinned))).toBe(false);

        setDefaultCreationDate(null);
        const explicitOnly = buildDocumentPDFBytes(doc(), { creationDate: OTHER });
        expect(Buffer.from(overridden).equals(Buffer.from(explicitOnly))).toBe(true);
    });

    it('changes the trailer /ID, not just the dates', () => {
        setDefaultCreationDate(PINNED);
        const a = latin1(buildDocumentPDFBytes(doc()));
        setDefaultCreationDate(OTHER);
        const b = latin1(buildDocumentPDFBytes(doc()));

        const idOf = (s: string): string => /\/ID \[<([0-9A-F]+)>/.exec(s)?.[1] ?? '';
        expect(idOf(a)).not.toBe('');
        expect(idOf(a)).not.toBe(idOf(b));
    });
});

describe('{date} header/footer placeholder', () => {
    it('resolves against the pinned instant instead of the wall clock', () => {
        const params: DocumentParams = {
            ...doc(),
            // The placeholder is substituted by the page-template renderer.
        };
        setDefaultCreationDate(PINNED);
        const pinned = latin1(buildDocumentPDFBytes(params, {
            headerTemplate: { left: '{date}' },
        }));
        // 2026-01-01 in UTC; the test process may run in any timezone, so
        // assert on the pinned-vs-pinned stability rather than on a literal.
        const again = latin1(buildDocumentPDFBytes(params, {
            headerTemplate: { left: '{date}' },
        }));
        expect(pinned).toBe(again);

        setDefaultCreationDate(OTHER);
        const other = latin1(buildDocumentPDFBytes(params, {
            headerTemplate: { left: '{date}' },
        }));
        expect(other).not.toBe(pinned);
    });

    it('shares one instant with /Info /CreationDate under an explicit override', () => {
        const bytes = latin1(buildDocumentPDFBytes(doc(), {
            headerTemplate: { left: '{date}' },
            creationDate: OTHER,
        }));
        const created = /\/CreationDate \(D:(\d{8})/.exec(bytes)?.[1] ?? '';
        expect(created).not.toBe('');
        // The placeholder renders YYYY-MM-DD from the same instant.
        const ymd = `${created.slice(0, 4)}-${created.slice(4, 6)}-${created.slice(6, 8)}`;
        expect(bytes).toContain(ymd);
    });
});
