/**
 * pdfnative â€” Compression Integration Tests
 * =============================================
 * End-to-end tests for FlateDecode compression in PDF output.
 *
 * Tests: compressed PDF structure, size reduction, encryption+compression,
 *        tagged+compression, backward compatibility.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { buildPDF, buildPDFBytes } from '../../src/core/pdf-builder.js';
import { buildDocumentPDF, buildDocumentPDFBytes } from '../../src/core/pdf-document.js';
import { initNodeCompression } from '../../src/core/pdf-compress.js';
import type { PdfParams } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';

let zlibInflateSync: (buf: Uint8Array) => Uint8Array;

// Initialize native zlib for ESM context
beforeAll(async () => {
    await initNodeCompression();
    const modName = 'node:zlib';
    const mod = await import(/* @vite-ignore */ modName) as { inflateSync: (buf: Uint8Array) => Uint8Array };
    zlibInflateSync = mod.inflateSync;
});

/** Minimal valid PdfParams for table builder. */
function makeParams(overrides?: Partial<PdfParams>): PdfParams {
    return {
        title: 'Compression Test',
        infoItems: [{ label: 'Account', value: 'FR76 1234' }],
        balanceText: 'â‚¬ 1,000.00',
        countText: '3 operations',
        headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
        rows: [
            { cells: ['2024-01-01', 'Opening', '', '1000.00', '1000.00'], type: 'credit', pointed: false },
            { cells: ['2024-01-02', 'Payment', '100.00', '', '900.00'], type: 'debit', pointed: false },
            { cells: ['2024-01-03', 'Salary', '', '3000.00', '3900.00'], type: 'credit', pointed: true },
        ],
        footerText: 'Generated by pdfnative',
        ...overrides,
    };
}

/** Minimal document params for document builder. */
function makeDocParams(): DocumentParams {
    return {
        title: 'Compressed Document',
        blocks: [
            { type: 'heading', text: 'Chapter One', level: 1 },
            { type: 'paragraph', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '.repeat(10) },
            { type: 'heading', text: 'Section 1.1', level: 2 },
            { type: 'paragraph', text: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '.repeat(5) },
            { type: 'list', items: ['First item', 'Second item', 'Third item'], style: 'bullet' },
        ],
        footerText: 'Document Builder Test',
    };
}

describe('Compressed PDF â€” Table Builder', () => {
    it('should contain /Filter /FlateDecode in streams when compress=true', () => {
        const pdf = buildPDF(makeParams(), { compress: true });
        expect(pdf).toContain('/Filter /FlateDecode');
    });

    it('should NOT contain /Filter /FlateDecode when compress=false', () => {
        const pdf = buildPDF(makeParams(), { compress: false });
        expect(pdf).not.toContain('/Filter /FlateDecode');
    });

    it('should NOT contain /Filter /FlateDecode by default (backward compat)', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf).not.toContain('/Filter /FlateDecode');
    });

    it('should produce valid PDF header and trailer when compressed', () => {
        const pdf = buildPDF(makeParams(), { compress: true });
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        expect(pdf).toMatch(/%%EOF$/);
        expect(pdf).toContain('xref');
        expect(pdf).toContain('startxref');
    });

    it('should produce smaller output when compressed (Latin)', () => {
        const rows = Array.from({ length: 50 }, (_, i) => ({
            cells: [`2024-01-${String(i + 1).padStart(2, '0')}`, `Transaction ${i + 1}`, '100.00', '', '900.00'],
            type: i % 2 === 0 ? 'credit' : 'debit',
            pointed: false,
        }));
        const params = makeParams({ rows });
        const uncompressed = buildPDFBytes(params, { compress: false });
        const compressed = buildPDFBytes(params, { compress: true });
        expect(compressed.length).toBeLessThan(uncompressed.length);
    });

    it('should produce valid xref offsets when compressed', () => {
        const pdf = buildPDF(makeParams(), { compress: true });
        // Parse xref section
        const xrefIdx = pdf.indexOf('xref\n');
        expect(xrefIdx).toBeGreaterThan(0);
        // Verify startxref points to xref
        const startxrefMatch = pdf.match(/startxref\n(\d+)\n/);
        expect(startxrefMatch).not.toBeNull();
        const startxref = Number(startxrefMatch![1]);
        expect(startxref).toBe(xrefIdx);
    });

    it('should contain catalog and page objects when compressed', () => {
        const pdf = buildPDF(makeParams(), { compress: true });
        expect(pdf).toContain('/Type /Catalog');
        expect(pdf).toContain('/Type /Pages');
        expect(pdf).toContain('/Type /Page');
    });

    it('compressed streams should decompress to valid content', () => {
        const pdf = buildPDF(makeParams(), { compress: true });
        // Extract a compressed stream between "stream\n" and "\nendstream"
        const streamRegex = /\/Filter \/FlateDecode \/Length (\d+).*?>>\nstream\n/g;
        const match = streamRegex.exec(pdf);
        expect(match).not.toBeNull();
        const streamStart = match!.index + match![0].length;
        const streamLen = Number(match![1]);
        const streamData = pdf.slice(streamStart, streamStart + streamLen);
        // Convert binary string to Uint8Array
        const bytes = new Uint8Array(streamData.length);
        for (let i = 0; i < streamData.length; i++) {
            bytes[i] = streamData.charCodeAt(i) & 0xFF;
        }
        // Should decompress without error
        const decompressed = zlibInflateSync(bytes);
        expect(decompressed.length).toBeGreaterThan(0);
    });
});

describe('Compressed PDF â€” Document Builder', () => {
    it('should contain /Filter /FlateDecode when compress=true', () => {
        const pdf = buildDocumentPDF(makeDocParams(), { compress: true });
        expect(pdf).toContain('/Filter /FlateDecode');
    });

    it('should produce smaller output when compressed', () => {
        const uncompressed = buildDocumentPDFBytes(makeDocParams(), { compress: false });
        const compressed = buildDocumentPDFBytes(makeDocParams(), { compress: true });
        expect(compressed.length).toBeLessThan(uncompressed.length);
    });

    it('should produce valid PDF structure when compressed', () => {
        const pdf = buildDocumentPDF(makeDocParams(), { compress: true });
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        expect(pdf).toMatch(/%%EOF$/);
        expect(pdf).toContain('/Type /Catalog');
    });
});

describe('Compressed + Encrypted PDF', () => {
    it('should support compress + encryption together (compressâ†’encrypt order)', () => {
        const pdf = buildPDF(makeParams(), {
            compress: true,
            encryption: {
                ownerPassword: 'testowner',
                algorithm: 'aes128',
            },
        });
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        expect(pdf).toContain('/Encrypt');
        // FlateDecode should be in the dict entries (before encryption scrambles stream data)
        expect(pdf).toContain('/Filter /FlateDecode');
    });

    it('should produce valid structure with AES-256 + compression', () => {
        const pdf = buildPDF(makeParams(), {
            compress: true,
            encryption: {
                ownerPassword: 'test256',
                algorithm: 'aes256',
            },
        });
        expect(pdf).toContain('/Encrypt');
        expect(pdf).toContain('/Filter /FlateDecode');
        expect(pdf).toMatch(/%%EOF$/);
    });

    it('document builder should support compress + encryption', () => {
        const pdf = buildDocumentPDF(makeDocParams(), {
            compress: true,
            encryption: {
                ownerPassword: 'docowner',
                algorithm: 'aes128',
            },
        });
        expect(pdf).toContain('/Filter /FlateDecode');
        expect(pdf).toContain('/Encrypt');
    });
});

describe('Compressed + Tagged PDF', () => {
    it('should support compress + tagged mode together', () => {
        const pdf = buildPDF(makeParams(), {
            compress: true,
            tagged: true,
        });
        expect(pdf).toContain('/Filter /FlateDecode');
        expect(pdf).toContain('/MarkInfo << /Marked true >>');
        expect(pdf).toContain('/StructTreeRoot');
    });

    it('should NOT compress XMP metadata stream in tagged mode', () => {
        const pdf = buildPDF(makeParams(), {
            compress: true,
            tagged: true,
        });
        // XMP metadata should contain /Type /Metadata without FlateDecode
        const xmpMatch = pdf.match(/\/Type \/Metadata \/Subtype \/XML \/Length \d+/);
        expect(xmpMatch).not.toBeNull();
        // Verify the XMP stream dict does NOT have FlateDecode
        expect(xmpMatch![0]).not.toContain('FlateDecode');
    });

    it('should compress ICC profile stream in tagged mode', () => {
        const pdf = buildPDF(makeParams(), {
            compress: true,
            tagged: true,
        });
        // ICC profile stream should have /N 3 and FlateDecode
        expect(pdf).toMatch(/\/Filter \/FlateDecode \/Length \d+.*?\/N 3|\/N 3.*?\/Filter \/FlateDecode/);
    });

    it('document builder should support compress + tagged', () => {
        const pdf = buildDocumentPDF(makeDocParams(), {
            compress: true,
            tagged: true,
        });
        expect(pdf).toContain('/Filter /FlateDecode');
        expect(pdf).toContain('/MarkInfo << /Marked true >>');
    });
});

describe('Compression size reduction benchmarks', () => {
    it('should reduce 100-row Latin table by >30%', () => {
        const rows = Array.from({ length: 100 }, (_, i) => ({
            cells: [`2024-01-${String((i % 28) + 1).padStart(2, '0')}`, `Transaction ${i + 1}`, `${(i * 10).toFixed(2)}`, '', `${(10000 - i * 10).toFixed(2)}`],
            type: i % 2 === 0 ? 'credit' : 'debit',
            pointed: i === 0,
        }));
        const params = makeParams({ rows });
        const uncompressed = buildPDFBytes(params);
        const compressed = buildPDFBytes(params, { compress: true });
        const ratio = 1 - compressed.length / uncompressed.length;
        expect(ratio).toBeGreaterThan(0.3);
    });
});
