import { describe, it, expect } from 'vitest';
import { buildPDF, buildPDFBytes } from '../../src/core/pdf-builder.js';
import { toBytes } from '../../src/core/pdf-stream.js';
import type { PdfParams, PdfRow } from '../../src/types/pdf-types.js';

/** Minimal valid PdfParams */
function makeParams(overrides?: Partial<PdfParams>): PdfParams {
    return {
        title: 'Integration Test',
        infoItems: [{ label: 'Account', value: '1234' }],
        balanceText: '€ 1,000.00',
        countText: '5 operations',
        headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
        rows: [
            { cells: ['2024-01-01', 'Opening balance', '', '1000.00', '1000.00'], type: 'credit', pointed: false },
            { cells: ['2024-01-02', 'Payment', '100.00', '', '900.00'], type: 'debit', pointed: false },
            { cells: ['2024-01-03', 'Salary', '', '3000.00', '3900.00'], type: 'credit', pointed: true },
        ],
        footerText: 'Generated by pdfnative — ISO 32000-1',
        ...overrides,
    };
}

describe('End-to-end PDF generation', () => {
    it('should generate a valid PDF binary string', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        expect(pdf).toMatch(/%%EOF$/);
    });

    it('should generate valid Uint8Array via buildPDFBytes', () => {
        const bytes = buildPDFBytes(makeParams());
        expect(bytes).toBeInstanceOf(Uint8Array);
        const header = String.fromCharCode(...bytes.slice(0, 8));
        expect(header).toBe('%PDF-1.4');
    });

    it('should contain xref table', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf).toContain('xref');
        expect(pdf).toContain('startxref');
    });

    it('should contain document catalog and pages', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf).toContain('/Type /Catalog');
        expect(pdf).toContain('/Type /Pages');
        expect(pdf).toContain('/Type /Page');
    });

    it('should embed visible title on page', () => {
        const pdf = buildPDF(makeParams({ title: 'My Visible Title' }));
        expect(pdf).toContain('My Visible Title');
    });

    it('should contain Helvetica font reference in Latin mode', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf).toContain('/BaseFont /Helvetica');
    });

    it('should handle empty rows', () => {
        const pdf = buildPDF(makeParams({ rows: [] }));
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        expect(pdf).toContain('%%EOF');
    });

    it('should handle pagination with many rows', () => {
        const rows: PdfRow[] = Array.from({ length: 100 }, (_, i) => ({
            cells: [`2024-01-${String(i + 1).padStart(2, '0')}`, `Item ${i}`, `${i}.00`, '', `${1000 - i}.00`],
            type: i % 2 === 0 ? 'credit' : 'debit',
            pointed: i % 10 === 0,
        }));
        const pdf = buildPDF(makeParams({ rows }));
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
        // Multiple pages should produce multiple /Type /Page entries
        const pageMatches = pdf.match(/\/Type \/Page[^s]/g);
        expect(pageMatches!.length).toBeGreaterThan(1);
    });

    it('should handle special PDF characters in text', () => {
        const pdf = buildPDF(makeParams({
            infoItems: [{ label: 'Test (parens)', value: 'Value \\with\\ backslash' }],
        }));
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
    });

    it('should handle long text truncation', () => {
        const longText = 'A'.repeat(500);
        const rows: PdfRow[] = [
            { cells: [longText, longText, '0.00', '', '0.00'], type: 'credit', pointed: false },
        ];
        const pdf = buildPDF(makeParams({ rows }));
        expect(pdf.startsWith('%PDF-1.4')).toBe(true);
    });

    it('should produce consistent output for same input', () => {
        const params = makeParams();
        const pdf1 = buildPDF(params);
        const pdf2 = buildPDF(params);
        expect(pdf1).toBe(pdf2);
    });

    it('should roundtrip through bytes correctly', () => {
        const pdfStr = buildPDF(makeParams());
        const bytes = toBytes(pdfStr);
        expect(bytes).toBeInstanceOf(Uint8Array);
        expect(bytes.length).toBeGreaterThan(0);
        // Verify first bytes match PDF header
        expect(bytes[0]).toBe(0x25); // %
        expect(bytes[1]).toBe(0x50); // P
        expect(bytes[2]).toBe(0x44); // D
        expect(bytes[3]).toBe(0x46); // F
    });

    it('should contain balance box text', () => {
        const pdf = buildPDF(makeParams({ balanceText: '€ 42,000.00' }));
        // PDF text is WinAnsi-encoded, check the text operator
        expect(pdf).toContain('42,000.00');
    });

    it('should contain footer on every page', () => {
        const rows: PdfRow[] = Array.from({ length: 100 }, () => ({
            cells: ['2024-01-01', 'Item', '10.00', '', '990.00'],
            type: 'debit',
            pointed: false,
        }));
        const pdf = buildPDF(makeParams({ rows, footerText: 'pdfnative-footer' }));
        const footerCount = (pdf.match(/pdfnative-footer/g) || []).length;
        const pageCount = (pdf.match(/\/Type \/Page[^s]/g) || []).length;
        expect(footerCount).toBe(pageCount);
    });
});

// ── Tagged PDF / PDF/A Integration Tests ─────────────────────────────

describe('Tagged PDF generation (tagged: true)', () => {
    it('should generate valid PDF with MarkInfo when tagged', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf.startsWith('%PDF-1.7')).toBe(true);
        expect(pdf).toContain('/MarkInfo << /Marked true >>');
    });

    it('should include StructTreeRoot in Catalog', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/StructTreeRoot');
        expect(pdf).toContain('/Type /StructTreeRoot');
    });

    it('should include structure elements', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/S /Document');
        expect(pdf).toContain('/S /Table');
        expect(pdf).toContain('/S /TR');
        expect(pdf).toContain('/S /TH');
        expect(pdf).toContain('/S /TD');
        expect(pdf).toContain('/S /P');
    });

    it('should include ParentTree number tree', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/Type /NumberTree');
        expect(pdf).toContain('/Nums');
    });

    it('should include /Span BDC...EMC marked content in content stream', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/Span');
        expect(pdf).toContain('BDC');
        expect(pdf).toContain('EMC');
    });

    it('should include /ActualText on marked content sequences', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/ActualText');
    });

    it('should include /StructParents on page objects', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/StructParents 0');
    });

    it('should include XMP metadata stream', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/Type /Metadata');
        expect(pdf).toContain('/Subtype /XML');
        expect(pdf).toContain('<?xpacket');
        expect(pdf).toContain('pdfaid:part');
    });

    it('should include OutputIntent for PDF/A', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('/Type /OutputIntent');
        expect(pdf).toContain('/S /GTS_PDFA1');
        expect(pdf).toContain('sRGB IEC61966-2.1');
        expect(pdf).toContain('/OutputIntents');
    });

    it('should include XMP PDF/A-2b conformance level', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('<pdfaid:part>2</pdfaid:part>');
        expect(pdf).toContain('<pdfaid:conformance>B</pdfaid:conformance>');
    });

    it('should have valid xref table in tagged mode', () => {
        const pdf = buildPDF(makeParams(), { tagged: true });
        expect(pdf).toContain('xref');
        expect(pdf).toContain('startxref');
        expect(pdf).toMatch(/%%EOF$/);
    });

    it('should produce valid bytes in tagged mode', () => {
        const bytes = buildPDFBytes(makeParams(), { tagged: true });
        expect(bytes).toBeInstanceOf(Uint8Array);
        const header = String.fromCharCode(...bytes.slice(0, 8));
        expect(header).toBe('%PDF-1.7');
    });

    it('should not include tagged structures when tagged is false', () => {
        const pdf = buildPDF(makeParams(), { tagged: false });
        expect(pdf).not.toContain('/MarkInfo');
        expect(pdf).not.toContain('/StructTreeRoot');
        expect(pdf).not.toContain('/Type /StructTreeRoot');
    });

    it('should not include tagged structures by default', () => {
        const pdf = buildPDF(makeParams());
        expect(pdf).not.toContain('/MarkInfo');
        expect(pdf).not.toContain('/StructTreeRoot');
    });

    it('should handle pagination in tagged mode', () => {
        const rows: PdfRow[] = Array.from({ length: 100 }, (_, i) => ({
            cells: [`2024-01-${String(i + 1).padStart(2, '0')}`, `Item ${i}`, `${i}.00`, '', `${1000 - i}.00`],
            type: i % 2 === 0 ? 'credit' : 'debit',
            pointed: false,
        }));
        const pdf = buildPDF(makeParams({ rows }), { tagged: true });
        expect(pdf.startsWith('%PDF-1.7')).toBe(true);
        expect(pdf).toContain('/MarkInfo');
        expect(pdf).toContain('/StructTreeRoot');
        const pageMatches = pdf.match(/\/Type \/Page[^s]/g);
        expect(pageMatches!.length).toBeGreaterThan(1);
        // Each page should have StructParents
        expect(pdf).toContain('/StructParents 0');
        expect(pdf).toContain('/StructParents 1');
    });

    it('should handle empty rows in tagged mode', () => {
        const pdf = buildPDF(makeParams({ rows: [] }), { tagged: true });
        expect(pdf.startsWith('%PDF-1.7')).toBe(true);
        expect(pdf).toContain('/MarkInfo');
    });
});
