/**
 * Financial statement sample data — 12 languages + multi-language + pagination.
 * Re-exported from the legacy monolithic file for backward compat.
 */

import type { LangSample } from '../helpers/types.js';

export const SAMPLES: LangSample[] = [
    {
        lang: 'latin',
        title: 'Monthly Account Statement',
        infoItems: [
            { label: 'Account', value: 'FR76 3000 6000 0112 3456 7890 189' },
            { label: 'Period', value: '01/01/2026 – 31/01/2026' },
            { label: 'Currency', value: 'EUR' },
        ],
        balanceText: 'Balance: € 12,345.67',
        countText: '8 transactions',
        headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
        rows: [
            { cells: ['01/01', 'Opening Balance', 'System', '+12,000.00', 'OK'], type: 'credit', pointed: false },
            { cells: ['01/05', 'Grocery Store', 'Food', '-85.50', ''], type: 'debit', pointed: false },
            { cells: ['01/10', 'Salary January', 'Income', '+3,200.00', 'OK'], type: 'credit', pointed: true },
            { cells: ['01/12', 'Electric Bill', 'Utilities', '-120.00', ''], type: 'debit', pointed: false },
            { cells: ['01/15', 'Restaurant', 'Food', '-45.00', ''], type: 'debit', pointed: false },
            { cells: ['01/20', 'Freelance Work', 'Income', '+800.00', 'OK'], type: 'credit', pointed: true },
            { cells: ['01/25', 'Internet Bill', 'Utilities', '-39.99', ''], type: 'debit', pointed: false },
            { cells: ['01/31', 'Transfer', 'Savings', '-1,500.00', 'X'], type: 'debit', pointed: false },
        ],
        footerText: 'Generated by pdfnative – ISO 32000-1 compliant',
    },
    { lang: 'th', title: 'รายงานบัญชีประจำเดือน', infoItems: [{ label: 'บัญชี', value: 'TH-1234-5678-9012' }, { label: 'ช่วงเวลา', value: '01/01/2569 – 31/01/2569' }, { label: 'สกุลเงิน', value: 'THB' }], balanceText: 'ยอดคงเหลือ: ฿ 345,678.90', countText: '6 รายการ', headers: ['วันที่', 'รายละเอียด', 'หมวดหมู่', 'จำนวน', 'สถานะ'], rows: [{ cells: ['01/01', 'ยอดยกมา', 'ระบบ', '+300,000.00', 'ตรวจ'], type: 'credit', pointed: false }, { cells: ['01/05', 'ซุปเปอร์มาร์เก็ต', 'อาหาร', '-2,500.00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'เงินเดือนมกราคม', 'รายได้', '+50,000.00', 'ตรวจ'], type: 'credit', pointed: true }, { cells: ['01/15', 'ค่าไฟฟ้า', 'สาธารณูปโภค', '-3,200.00', ''], type: 'debit', pointed: false }, { cells: ['01/20', 'งานอิสระ', 'รายได้', '+15,000.00', 'ตรวจ'], type: 'credit', pointed: true }, { cells: ['01/31', 'โอนเงิน', 'ออมทรัพย์', '-13,621.10', 'X'], type: 'debit', pointed: false }], footerText: 'สร้างโดย pdfnative – มาตรฐาน ISO 32000-1' },
    { lang: 'ja', title: '月次口座明細書', infoItems: [{ label: '口座番号', value: 'JP-0001-2345-6789' }, { label: '期間', value: '2026年1月1日 ～ 2026年1月31日' }, { label: '通貨', value: 'JPY' }], balanceText: '残高: ¥ 1,234,567', countText: '5 件の取引', headers: ['日付', '摘要', '区分', '金額', '状態'], rows: [{ cells: ['01/01', '繰越残高', 'システム', '+1,000,000', '済'], type: 'credit', pointed: false }, { cells: ['01/07', 'コンビニ', '食費', '-1,200', ''], type: 'debit', pointed: false }, { cells: ['01/10', '給与振込', '収入', '+280,000', '済'], type: 'credit', pointed: true }, { cells: ['01/20', '電気代', '光熱費', '-8,500', ''], type: 'debit', pointed: false }, { cells: ['01/31', '貯蓄振替', '貯蓄', '-35,733', 'X'], type: 'debit', pointed: false }], footerText: 'pdfnative により生成 – ISO 32000-1 準拠' },
    { lang: 'zh', title: '月度账户对账单', infoItems: [{ label: '账户', value: 'CN-6200-0000-1234-5678' }, { label: '期间', value: '2026年1月1日 至 2026年1月31日' }, { label: '币种', value: 'CNY' }], balanceText: '余额: ¥ 98,765.43', countText: '5 笔交易', headers: ['日期', '说明', '类别', '金额', '状态'], rows: [{ cells: ['01/01', '期初余额', '系统', '+80,000.00', '已核'], type: 'credit', pointed: false }, { cells: ['01/08', '超市购物', '食品', '-520.00', ''], type: 'debit', pointed: false }, { cells: ['01/10', '工资到账', '收入', '+22,000.00', '已核'], type: 'credit', pointed: true }, { cells: ['01/18', '水电费', '公共', '-1,200.00', ''], type: 'debit', pointed: false }, { cells: ['01/31', '储蓄转账', '储蓄', '-1,514.57', 'X'], type: 'debit', pointed: false }], footerText: '由 pdfnative 生成 – 符合 ISO 32000-1 标准' },
    { lang: 'ko', title: '월별 계좌 명세서', infoItems: [{ label: '계좌', value: 'KR-110-123-456789' }, { label: '기간', value: '2026년 1월 1일 ~ 2026년 1월 31일' }, { label: '통화', value: 'KRW' }], balanceText: '잔액: ₩ 5,678,900', countText: '5 건의 거래', headers: ['날짜', '설명', '분류', '금액', '상태'], rows: [{ cells: ['01/01', '이월 잔액', '시스템', '+5,000,000', '확인'], type: 'credit', pointed: false }, { cells: ['01/06', '마트 구매', '식비', '-85,000', ''], type: 'debit', pointed: false }, { cells: ['01/10', '급여 입금', '수입', '+900,000', '확인'], type: 'credit', pointed: true }, { cells: ['01/22', '전기요금', '공과금', '-65,000', ''], type: 'debit', pointed: false }, { cells: ['01/31', '적금 이체', '저축', '-71,100', 'X'], type: 'debit', pointed: false }], footerText: 'pdfnative로 생성 – ISO 32000-1 준수' },
    { lang: 'el', title: 'Μηνιαία Κατάσταση Λογαριασμού', infoItems: [{ label: 'Λογαριασμός', value: 'GR-1601-0400-0400-0123-4567-890' }, { label: 'Περίοδος', value: '01/01/2026 – 31/01/2026' }, { label: 'Νόμισμα', value: 'EUR' }], balanceText: 'Υπόλοιπο: € 4,567.89', countText: '5 συναλλαγές', headers: ['Ημ/νία', 'Περιγραφή', 'Κατηγορία', 'Ποσό', 'Κατάσταση'], rows: [{ cells: ['01/01', 'Υπόλοιπο μεταφοράς', 'Σύστημα', '+3,500.00', 'Ελ.'], type: 'credit', pointed: false }, { cells: ['01/05', 'Σούπερ μάρκετ', 'Τρόφιμα', '-120.50', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'Μισθός Ιανουαρίου', 'Εισόδημα', '+1,500.00', 'Ελ.'], type: 'credit', pointed: true }, { cells: ['01/18', 'Λογαριασμός ΔΕΗ', 'Κοινωφελή', '-85.00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'Μεταφορά', 'Αποταμίευση', '-226.61', 'X'], type: 'debit', pointed: false }], footerText: 'Δημιουργήθηκε από pdfnative – ISO 32000-1' },
    { lang: 'hi', title: 'मासिक खाता विवरण', infoItems: [{ label: 'खाता', value: 'IN-SBIN-00001234567890' }, { label: 'अवधि', value: '01/01/2026 – 31/01/2026' }, { label: 'मुद्रा', value: 'INR' }], balanceText: 'शेष: ₹ 2,34,567.00', countText: '5 लेनदेन', headers: ['दिनांक', 'विवरण', 'श्रेणी', 'राशि', 'स्थिति'], rows: [{ cells: ['01/01', 'प्रारंभिक शेष', 'सिस्टम', '+2,00,000.00', 'जाँचा'], type: 'credit', pointed: false }, { cells: ['01/05', 'किराना स्टोर', 'खाद्य', '-3,500.00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'वेतन जनवरी', 'आय', '+45,000.00', 'जाँचा'], type: 'credit', pointed: true }, { cells: ['01/20', 'बिजली बिल', 'उपयोगिता', '-2,800.00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'बचत स्थानांतरण', 'बचत', '-4,133.00', 'X'], type: 'debit', pointed: false }], footerText: 'pdfnative द्वारा निर्मित – ISO 32000-1 अनुरूप' },
    { lang: 'tr', title: 'Aylık Hesap Özeti', infoItems: [{ label: 'Hesap', value: 'TR33 0006 1005 1978 6457 8413 26' }, { label: 'Dönem', value: '01/01/2026 – 31/01/2026' }, { label: 'Para Birimi', value: 'TRY' }], balanceText: 'Bakiye: ₺ 45.678,90', countText: '5 işlem', headers: ['Tarih', 'Açıklama', 'Kategori', 'Tutar', 'Durum'], rows: [{ cells: ['01/01', 'Açılış bakiyesi', 'Sistem', '+40.000,00', 'Onayl.'], type: 'credit', pointed: false }, { cells: ['01/05', 'Süpermarket alışverişi', 'Gıda', '-1.250,00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'Maaş Ocak', 'Gelir', '+8.500,00', 'Onayl.'], type: 'credit', pointed: true }, { cells: ['01/18', 'Elektrik faturası', 'Fatura', '-650,00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'Tasarruf transferi', 'Birikim', '-921,10', 'X'], type: 'debit', pointed: false }], footerText: 'pdfnative tarafından oluşturuldu – ISO 32000-1 uyumlu' },
    { lang: 'vi', title: 'Sao Kê Tài Khoản Hàng Tháng', infoItems: [{ label: 'Tài khoản', value: 'VN-1900-0000-123456' }, { label: 'Kỳ hạn', value: '01/01/2026 – 31/01/2026' }, { label: 'Tiền tệ', value: 'VND' }], balanceText: 'Số dư: ₫ 123.456.789', countText: '5 giao dịch', headers: ['Ngày', 'Mô tả', 'Loại', 'Số tiền', 'Trạng thái'], rows: [{ cells: ['01/01', 'Số dư đầu kỳ', 'Hệ thống', '+100.000.000', 'Đã duyệt'], type: 'credit', pointed: false }, { cells: ['01/06', 'Siêu thị', 'Thực phẩm', '-850.000', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'Lương tháng 1', 'Thu nhập', '+25.000.000', 'Đã duyệt'], type: 'credit', pointed: true }, { cells: ['01/20', 'Tiền điện', 'Tiện ích', '-1.200.000', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'Chuyển tiết kiệm', 'Tiết kiệm', '-493.211', 'X'], type: 'debit', pointed: false }], footerText: 'Tạo bởi pdfnative – Tuân thủ ISO 32000-1' },
    { lang: 'pl', title: 'Miesięczny Wyciąg Bankowy', infoItems: [{ label: 'Konto', value: 'PL61 1090 1014 0000 0712 1981 2874' }, { label: 'Okres', value: '01/01/2026 – 31/01/2026' }, { label: 'Waluta', value: 'PLN' }], balanceText: 'Saldo: 15 678,90 zł', countText: '5 transakcji', headers: ['Data', 'Opis', 'Kategoria', 'Kwota', 'Status'], rows: [{ cells: ['01/01', 'Saldo początkowe', 'System', '+12.000,00', 'Zat.'], type: 'credit', pointed: false }, { cells: ['01/05', 'Zakupy spożywcze', 'Żywność', '-350,00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'Wynagrodzenie styczeń', 'Dochód', '+5.200,00', 'Zat.'], type: 'credit', pointed: true }, { cells: ['01/18', 'Rachunek za prąd', 'Media', '-280,00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'Przelew na lokatę', 'Oszczędności', '-891,10', 'X'], type: 'debit', pointed: false }], footerText: 'Wygenerowano przez pdfnative – ISO 32000-1' },
    { lang: 'ar', title: 'كشف حساب شهري', infoItems: [{ label: 'الحساب', value: 'SA03 8000 0000 6080 1016 7519' }, { label: 'الفترة', value: '01/01/2026 – 31/01/2026' }, { label: 'العملة', value: 'SAR' }], balanceText: 'الرصيد: ﷼ 45,230.00', countText: '5 معاملات', headers: ['التاريخ', 'الوصف', 'الفئة', 'المبلغ', 'الحالة'], rows: [{ cells: ['01/01', 'رصيد افتتاحي', 'نظام', '+40,000.00', 'مراجع'], type: 'credit', pointed: false }, { cells: ['01/05', 'بقالة ومواد غذائية', 'طعام', '-1,200.00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'راتب يناير', 'دخل', '+8,500.00', 'مراجع'], type: 'credit', pointed: true }, { cells: ['01/18', 'فاتورة الكهرباء', 'خدمات', '-750.00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'تحويل ادخار', 'ادخار', '-1,320.00', 'X'], type: 'debit', pointed: false }], footerText: 'تم الإنشاء بواسطة pdfnative – متوافق مع ISO 32000-1' },
    { lang: 'he', title: 'דף חשבון חודשי', infoItems: [{ label: 'חשבון', value: 'IL62 0108 0000 0009 9999 999' }, { label: 'תקופה', value: '01/01/2026 – 31/01/2026' }, { label: 'מטבע', value: 'ILS' }], balanceText: 'יתרה: ₪ 28,450.00', countText: '5 תנועות', headers: ['תאריך', 'תיאור', 'קטגוריה', 'סכום', 'סטטוס'], rows: [{ cells: ['01/01', 'יתרת פתיחה', 'מערכת', '+25,000.00', 'מאושר'], type: 'credit', pointed: false }, { cells: ['01/05', 'קניות מכולת', 'מזון', '-850.00', ''], type: 'debit', pointed: false }, { cells: ['01/10', 'משכורת ינואר', 'הכנסה', '+6,200.00', 'מאושר'], type: 'credit', pointed: true }, { cells: ['01/20', 'חשבון חשמל', 'שירותים', '-520.00', ''], type: 'debit', pointed: false }, { cells: ['01/31', 'העברה לחיסכון', 'חיסכון', '-1,380.00', 'X'], type: 'debit', pointed: false }], footerText: 'נוצר באמצעות pdfnative – תואם ISO 32000-1' },
];

export const MULTI_LANG_SAMPLE: LangSample = {
    lang: 'multi',
    title: 'Multi-Language Statement',
    infoItems: [{ label: 'Account', value: 'MULTI-LANG-TEST-001' }, { label: 'Period', value: '01/2026' }],
    balanceText: 'Balance: € 99,999.99',
    countText: '11 transactions',
    headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
    rows: [
        { cells: ['01/01', 'English transaction', 'Test', '+1,000.00', 'OK'], type: 'credit', pointed: false },
        { cells: ['01/02', 'รายการไทย', 'ทดสอบ', '-500.00', ''], type: 'debit', pointed: false },
        { cells: ['01/03', '日本語の取引', 'テスト', '+2,000.00', '済'], type: 'credit', pointed: true },
        { cells: ['01/04', '中文交易记录', '测试', '-300.00', ''], type: 'debit', pointed: false },
        { cells: ['01/05', '한국어 거래', '테스트', '+1,500.00', '확인'], type: 'credit', pointed: false },
        { cells: ['01/06', 'Ελληνική συναλλαγή', 'Δοκιμή', '-200.00', ''], type: 'debit', pointed: false },
        { cells: ['01/07', 'हिन्दी लेनदेन', 'परीक्षण', '+800.00', 'जाँचा'], type: 'credit', pointed: true },
        { cells: ['01/08', 'Türkçe işlem', 'Test', '-150.00', ''], type: 'debit', pointed: false },
        { cells: ['01/09', 'Giao dịch tiếng Việt', 'Kiểm tra', '+350.00', 'Đã duyệt'], type: 'credit', pointed: false },
        { cells: ['01/10', 'معاملة عربية', 'اختبار', '+600.00', 'مراجع'], type: 'credit', pointed: false },
        { cells: ['01/11', 'עסקה בעברית', 'בדיקה', '-250.00', 'מאושר'], type: 'debit', pointed: false },
    ],
    footerText: 'pdfnative – Multi-language generation test',
};

export const PAGINATION_SAMPLE: LangSample = {
    lang: 'pagination',
    title: 'Pagination Test – 200 Rows',
    infoItems: [
        { label: 'Account', value: 'PAGINATION-TEST-001' },
        { label: 'Period', value: 'Full Year 2026' },
        { label: 'Type', value: 'Multi-page layout validation' },
    ],
    balanceText: 'Balance: € 100,000.00',
    countText: '200 transactions',
    headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
    rows: Array.from({ length: 200 }, (_, i) => ({
        cells: [
            `${String((i % 28) + 1).padStart(2, '0')}/${String((i % 12) + 1).padStart(2, '0')}`,
            `Transaction number ${i + 1} – Lorem ipsum dolor sit amet`,
            i % 3 === 0 ? 'Income' : i % 3 === 1 ? 'Expense' : 'Transfer',
            `${i % 2 === 0 ? '+' : '-'}${(Math.random() * 5000).toFixed(2)}`,
            i % 4 === 0 ? 'OK' : '',
        ],
        type: i % 2 === 0 ? 'credit' : 'debit',
        pointed: i % 7 === 0,
    })),
    footerText: 'pdfnative – Pagination test (should be ~7 pages)',
};
