/**
 * PRE-BUILT COLOUR-EMOJI FONT DATA — NotoColorEmoji-Regular (curated subset)
 * ==========================================================================
 * Generated by: scripts/build-color-emoji-data.ts
 * Source: NotoColorEmoji-Regular.ttf (OFL-1.1)
 * Colour glyphs: 1167 (curated). COLR/CPAL → solid + linear + radial paints.
 * Plus curated flag / ZWJ sequences (see scripts/lib/curated-emoji-sequences.ts).
 *
 * Opt in:
 *   import { registerFont } from 'pdfnative';
 *   registerFont('emoji', () => import('pdfnative/fonts/noto-color-emoji-data.js'));
 *
 * DO NOT EDIT — regenerate with: npx tsx scripts/build-color-emoji-data.ts
 */

import type { FontData } from '../src/types/pdf-types.js';

export declare const metrics: FontData['metrics'];
export declare const fontName: string;
export declare const cmap: Record<number, number>;
export declare const defaultWidth: number;
export declare const widths: Record<number, number>;
export declare const pdfWidthArray: string;
export declare const gsub: Record<number, number>;
export declare const ligatures: null;
export declare const markAnchors: null;
export declare const mark2mark: null;
export declare const sequences: FontData['sequences'];
export declare const colorGlyphs: NonNullable<FontData['colorGlyphs']>;
export declare const ttfBase64: string;
