import { describe, it, expect } from 'vitest';
import * as colorEmoji from '../../fonts/noto-color-emoji-data.js';
import { buildDocumentPDFBytes } from '../../src/core/pdf-document.js';
import { openPdf } from '../../src/parser/pdf-reader.js';
import { CURATED_EMOJI } from '../../scripts/lib/curated-emoji.js';
import type { FontData, FontEntry } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';

// Guards the committed curated colour-emoji data module
// (fonts/noto-color-emoji-data.js, generated by scripts/build-color-emoji-data.ts).

describe('noto-color-emoji-data module', () => {
    it('exports a valid colour FontData shape', () => {
        expect(colorEmoji.fontName).toBe('NotoColorEmoji-Regular');
        expect(typeof colorEmoji.ttfBase64).toBe('string');
        expect(colorEmoji.ttfBase64.length).toBeGreaterThan(1000);
        expect(colorEmoji.metrics.unitsPerEm).toBeGreaterThan(0);
        expect(Object.keys(colorEmoji.colorGlyphs).length).toBeGreaterThan(100);
        expect(Object.keys(colorEmoji.cmap).length).toBeGreaterThan(100);
    });

    it('bundles the expanded curated set (~850) within the size budget', () => {
        // Expanded from 221 to ~850 in v1.6.0.
        expect(CURATED_EMOJI.length).toBeGreaterThanOrEqual(800);
        expect(CURATED_EMOJI.length).toBeLessThanOrEqual(900);
        // No duplicates.
        expect(new Set(CURATED_EMOJI).size).toBe(CURATED_EMOJI.length);
        // cmap covers (nearly) the whole curated list.
        const cmapKeys = Object.keys(colorEmoji.cmap).length;
        expect(cmapKeys).toBeGreaterThanOrEqual(CURATED_EMOJI.length - 5);
        // Module stays within the ~3.5 MB npm-tarball budget.
        const sizeKb = Buffer.byteLength(colorEmoji.ttfBase64) / 1024;
        expect(sizeKb).toBeLessThan(3584);
    });

    it('every cmap entry resolves to a colour glyph with width metrics', () => {
        for (const [cpStr, gid] of Object.entries(colorEmoji.cmap)) {
            expect(colorEmoji.colorGlyphs[gid as number]).toBeDefined();
            expect(typeof colorEmoji.widths[gid as number] === 'number' || colorEmoji.metrics).toBeTruthy();
            void cpStr;
        }
    });

    it('covers newly-added codepoints beyond the original 221 subset', () => {
        // Symbols/pictographs and extended emoji that were NOT in the lean set.
        for (const cp of [0x1f321, 0x1f4c5, 0x1f6d2, 0x1fa79, 0x1f9ee]) {
            const gid = colorEmoji.cmap[cp];
            if (gid !== undefined) {
                expect(colorEmoji.colorGlyphs[gid]).toBeDefined();
            }
        }
        // At least some of those extended codepoints must be present.
        const present = [0x1f321, 0x1f4c5, 0x1f6d2, 0x1fa79, 0x1f9ee].filter(cp => colorEmoji.cmap[cp] !== undefined);
        expect(present.length).toBeGreaterThan(0);
    });

    it('maps common emoji codepoints to colour glyphs', () => {
        const grin = colorEmoji.cmap[0x1f600];
        expect(grin).toBeGreaterThan(0);
        expect(colorEmoji.colorGlyphs[grin]).toBeDefined();
        expect(colorEmoji.colorGlyphs[grin].layers.length).toBeGreaterThan(0);
    });

    it('renders colour emoji as Form XObjects in a document', () => {
        const fontData = colorEmoji as unknown as FontData;
        const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
        const params: DocumentParams = {
            title: 'Colour Emoji Module',
            blocks: [{ type: 'paragraph', text: 'Hi \u{1F600} \u{2764} \u{1F44D} there' }],
            fontEntries: [entry],
        };
        const bytes = buildDocumentPDFBytes(params);
        const pdf = Buffer.from(bytes).toString('latin1');
        expect(pdf).toContain('/Subtype /Form');
        expect(pdf).toMatch(/\/CEm\d+ Do/);
        const doc = openPdf(bytes);
        expect(doc.pageCount).toBe(1);
    });
});
