import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import * as colorEmoji from '../../fonts/noto-color-emoji-data.js';
import { buildDocumentPDFBytes } from '../../src/core/pdf-document.js';
import { isAlphaRamp, renderColorGlyph } from '../../src/core/pdf-color-glyph.js';
import { extractGlyphContours, parseGlyfFont } from '../../src/fonts/glyf-outline.js';
import { openPdf } from '../../src/parser/pdf-reader.js';
import { CURATED_EMOJI } from '../../scripts/lib/curated-emoji.js';
import { SKIN_TONE_BASES } from '../../scripts/lib/curated-emoji-sequences.js';
import type { PdfDict, PdfValue } from '../../src/parser/pdf-object-parser.js';
import type { ColorGlyph, FontData, FontEntry } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';

// Guards the committed curated colour-emoji data module
// (fonts/noto-color-emoji-data.js, generated by scripts/build-color-emoji-data.ts).

describe('noto-color-emoji-data module', () => {
    it('exports a valid colour FontData shape', () => {
        expect(colorEmoji.fontName).toBe('NotoColorEmoji-Regular');
        expect(typeof colorEmoji.ttfBase64).toBe('string');
        expect(colorEmoji.ttfBase64.length).toBeGreaterThan(1000);
        expect(colorEmoji.metrics.unitsPerEm).toBeGreaterThan(0);
        expect(Object.keys(colorEmoji.colorGlyphs).length).toBeGreaterThan(100);
        expect(Object.keys(colorEmoji.cmap).length).toBeGreaterThan(100);
    });

    it('bundles the expanded curated set (~1190) within the size budget', () => {
        // Expanded from 221 to ~850, then to 1167 (Misc S&P completion +
        // full Transport & Map) in v1.6.0, then to 1189 in v1.8.0 once the
        // COLRv1 parser stopped dropping glyphs built on transforms and masks.
        expect(CURATED_EMOJI.length).toBeGreaterThanOrEqual(1050);
        expect(CURATED_EMOJI.length).toBeLessThanOrEqual(1250);
        // No duplicates.
        expect(new Set(CURATED_EMOJI).size).toBe(CURATED_EMOJI.length);
        // Module stays within the npm-tarball budget (raised 4096 → 5120 KB
        // in v1.7.0 for the curated flag/ZWJ sequence set). This measures
        // the shipped file. It used to measure only the embedded font
        // (`ttfBase64`), about half the module, so it passed with twice the
        // headroom the budget really had and could not catch a regression.
        const moduleUrl = new URL('../../fonts/noto-color-emoji-data.js', import.meta.url);
        const sizeKb = readFileSync(fileURLToPath(moduleUrl)).byteLength / 1024;
        expect(sizeKb).toBeLessThan(5120);
    });

    it('every curated codepoint maps to a colour glyph', () => {
        // Hard guarantee: the bundled cmap covers the WHOLE curated list, so
        // no curated emoji can ever regress to `.notdef` tofu. (The list is
        // pruned at build time of codepoints the font has no COLR glyph for.)
        for (const cp of CURATED_EMOJI) {
            const gid = colorEmoji.cmap[cp];
            expect(gid, `U+${cp.toString(16).toUpperCase()} missing from cmap`).toBeDefined();
            expect(colorEmoji.colorGlyphs[gid as number], `U+${cp.toString(16).toUpperCase()} has no colour glyph`).toBeDefined();
        }
    });

    it('every cmap entry resolves to a colour glyph with width metrics', () => {
        for (const [cpStr, gid] of Object.entries(colorEmoji.cmap)) {
            expect(colorEmoji.colorGlyphs[gid as number]).toBeDefined();
            expect(typeof colorEmoji.widths[gid as number] === 'number' || colorEmoji.metrics).toBeTruthy();
            void cpStr;
        }
    });

    it('covers the ranges the v1.6.0 expansion completed', () => {
        // The 15 codepoints that rendered as tofu in color-emoji-basic.pdf
        // before the Misc S&P / Transport & Map completion, plus a spot-check
        // of each restored range.
        const restored = [
            0x1f5a4, 0x1f525, 0x1f4af, 0x1f4aa, 0x1f697, 0x1f695, 0x1f68c,
            0x1f680, 0x1f6a2, 0x1f4f1, 0x1f4cc, 0x1f512, 0x1f511, 0x1f4b0,
            0x1f4b5,
            0x1f4c5, 0x1f50d, 0x1f550, 0x1f6d2, 0x1f6f8,
        ];
        for (const cp of restored) {
            const gid = colorEmoji.cmap[cp];
            expect(gid, `U+${cp.toString(16).toUpperCase()} missing from cmap`).toBeDefined();
            expect(colorEmoji.colorGlyphs[gid as number]).toBeDefined();
        }
        // Extended-A (U+1FA70-1FAFF) is documented as NOT bundled (CLI-only).
        expect(colorEmoji.cmap[0x1fa79]).toBeUndefined();
    });

    it('covers every emoji used by the colour-emoji showcase generator', () => {
        // Cross-check: scripts/generators/color-emoji-showcase.ts promises
        // "zero .notdef tofu" — hold it to that by asserting every emoji
        // codepoint in its source is in the bundled cmap.
        const src = readFileSync(
            fileURLToPath(new URL('../../scripts/generators/color-emoji-showcase.ts', import.meta.url)),
            'utf8',
        );
        const isEmojiBlock = (cp: number): boolean =>
            (cp >= 0x231a && cp <= 0x231b) || (cp >= 0x23e9 && cp <= 0x23fa) ||
            (cp >= 0x2600 && cp <= 0x27bf) || (cp >= 0x2b00 && cp <= 0x2bff) ||
            (cp >= 0x1f300 && cp <= 0x1faff);
        const used = new Set<number>();
        for (const ch of src) {
            const cp = ch.codePointAt(0) as number;
            if (isEmojiBlock(cp)) used.add(cp);
        }
        expect(used.size).toBeGreaterThan(50);
        // A codepoint is covered when the cmap maps it directly OR it only
        // ever appears as a component of a bundled sequence (flags/ZWJ, whose
        // ligature glyph renders the whole run — v1.7.0).
        const sequenceComponents = new Set<number>();
        const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']> | null;
        if (seqs) {
            for (const [first, entries] of Object.entries(seqs)) {
                sequenceComponents.add(Number(first));
                for (const entry of entries) for (let k = 1; k < entry.length; k++) sequenceComponents.add(entry[k]);
            }
        }
        for (const cp of used) {
            const gid = colorEmoji.cmap[cp];
            if (gid === undefined) {
                expect(sequenceComponents.has(cp), `showcase uses U+${cp.toString(16).toUpperCase()} but it is neither in the bundled cmap nor part of a bundled sequence`).toBe(true);
                continue;
            }
            expect(colorEmoji.colorGlyphs[gid as number]).toBeDefined();
        }
    });

    it('maps common emoji codepoints to colour glyphs', () => {
        const grin = colorEmoji.cmap[0x1f600];
        expect(grin).toBeGreaterThan(0);
        expect(colorEmoji.colorGlyphs[grin]).toBeDefined();
        expect(colorEmoji.colorGlyphs[grin].layers.length).toBeGreaterThan(0);
    });

    it('renders colour emoji as Form XObjects in a document', () => {
        const fontData = colorEmoji as unknown as FontData;
        const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
        const params: DocumentParams = {
            title: 'Colour Emoji Module',
            blocks: [{ type: 'paragraph', text: 'Hi \u{1F600} \u{2764} \u{1F44D} there' }],
            fontEntries: [entry],
        };
        const bytes = buildDocumentPDFBytes(params);
        const pdf = Buffer.from(bytes).toString('latin1');
        expect(pdf).toContain('/Subtype /Form');
        expect(pdf).toMatch(/\/CEm\d+ Do/);
        const doc = openPdf(bytes);
        expect(doc.pageCount).toBe(1);
    });

    // ── v1.7.0: bundled flag / ZWJ sequences ─────────────────────────

    describe('sequences table', () => {
        it('exports a codepoint-keyed sequences table', () => {
            expect(colorEmoji.sequences).toBeTruthy();
            const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']>;
            expect(Object.keys(seqs).length).toBeGreaterThan(20);
        });

        it('every sequence entry resolves to a colour ligature glyph with a width', () => {
            const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']>;
            for (const [firstCp, entries] of Object.entries(seqs)) {
                for (const entry of entries) {
                    const gid = entry[0];
                    expect(entry.length, `sequence at U+${Number(firstCp).toString(16)}`).toBeGreaterThanOrEqual(2);
                    expect(colorEmoji.colorGlyphs[gid], `lig gid ${gid} has no colour glyph`).toBeDefined();
                    expect(colorEmoji.widths[gid], `lig gid ${gid} has no width`).toBeDefined();
                }
            }
        });

        it('keeps entries longest-first per first-codepoint bucket', () => {
            const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']>;
            for (const entries of Object.values(seqs)) {
                for (let i = 1; i < entries.length; i++) {
                    expect(entries[i - 1].length).toBeGreaterThanOrEqual(entries[i].length);
                }
            }
        });

        it('bundles the curated flags (FR, DE, JP, EU…) and ZWJ sets', () => {
            const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']>;
            const has = (cps: readonly number[]): boolean => {
                const bucket = seqs[cps[0]];
                return Boolean(bucket?.some(e =>
                    e.length - 1 === cps.length - 1 && cps.slice(1).every((c, k) => e[1 + k] === c)));
            };
            expect(has([0x1F1EB, 0x1F1F7])).toBe(true); // 🇫🇷
            expect(has([0x1F1E9, 0x1F1EA])).toBe(true); // 🇩🇪
            expect(has([0x1F1EF, 0x1F1F5])).toBe(true); // 🇯🇵
            expect(has([0x1F1EA, 0x1F1FA])).toBe(true); // 🇪🇺
            expect(has([0x1F468, 0x200D, 0x1F4BB])).toBe(true); // 👨‍💻
            expect(has([0x1F3F4, 0x200D, 0x2620, 0xFE0F])).toBe(true); // 🏴‍☠️
        });

        it('bundles every curated skin-tone base in all five tones (v1.8.0)', () => {
            const seqs = colorEmoji.sequences as NonNullable<FontData['sequences']>;
            for (const base of SKIN_TONE_BASES) {
                const gids = new Set<number>();
                for (const tone of [0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF]) {
                    const entry = seqs[base]?.find(e => e.length === 2 && e[1] === tone);
                    const label = `U+${base.toString(16).toUpperCase()} U+${tone.toString(16).toUpperCase()}`;
                    expect(entry, `${label} not bundled`).toBeDefined();
                    const gid = (entry as readonly number[])[0];
                    expect(colorEmoji.colorGlyphs[gid], `${label} has no colour glyph`).toBeDefined();
                    // A toned form is its own glyph, never the untoned base.
                    expect(gid).not.toBe(colorEmoji.cmap[base]);
                    gids.add(gid);
                }
                expect(gids.size, `U+${base.toString(16).toUpperCase()} tones share glyphs`).toBe(5);
            }
        });

        it('renders a toned gesture as one colour glyph, not base plus swatch', () => {
            const fontData = colorEmoji as unknown as FontData;
            const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
            const bytes = buildDocumentPDFBytes({
                title: 'Skin tones',
                blocks: [{ type: 'paragraph', text: '\u{1F44D}\u{1F3FD}' }],
                fontEntries: [entry],
            });
            const doOps = Buffer.from(bytes).toString('latin1').match(/\/CEm\d+ Do/g) ?? [];
            expect(doOps.length).toBe(1);
        });

        it('keeps joiners and regional indicators OUT of the cmap', () => {
            // The "every cmap entry → colour glyph" invariant depends on it.
            expect(colorEmoji.cmap[0x200D]).toBeUndefined();
            expect(colorEmoji.cmap[0xFE0F]).toBeUndefined();
            expect(colorEmoji.cmap[0x1F1EB]).toBeUndefined();
        });

        it('renders a flag and a ZWJ sequence as single colour glyphs', () => {
            const fontData = colorEmoji as unknown as FontData;
            const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
            const params: DocumentParams = {
                title: 'Sequences',
                blocks: [{ type: 'paragraph', text: 'Flags \u{1F1EB}\u{1F1F7} \u{1F1E9}\u{1F1EA} and \u{1F468}\u{200D}\u{1F4BB}' }],
                fontEntries: [entry],
            };
            const bytes = buildDocumentPDFBytes(params);
            const pdf = Buffer.from(bytes).toString('latin1');
            const doOps = pdf.match(/\/CEm\d+ Do/g) ?? [];
            // 2 flags + 1 technologist = 3 colour form draws.
            expect(doOps.length).toBeGreaterThanOrEqual(3);
            expect(openPdf(bytes).pageCount).toBe(1);
        });
    });

    // ── v1.8.0: alpha-ramp gradients ──────────────────────────────────
    // Noto draws soft shadows as gradients whose stops share one RGB and
    // fade only in alpha. A PDF shading has no per-stop alpha, so the
    // renderer used to paint them as flat opaque discs — U+1F469 WOMAN's
    // last layer covered the whole face. Such layers are now omitted.

    describe('alpha-ramp gradients', () => {
        const mod = colorEmoji as unknown as {
            ttfBase64: string; colorGlyphs: Record<number, ColorGlyph>; cmap: Record<number, number>;
            metrics: { unitsPerEm: number };
        };
        const glyf = parseGlyfFont(new Uint8Array(Buffer.from(mod.ttfBase64, 'base64')));
        const outlines = (gid: number): ReturnType<typeof extractGlyphContours> =>
            glyf ? extractGlyphContours(glyf, gid) : [];
        const render = (gid: number): ReturnType<typeof renderColorGlyph> =>
            renderColorGlyph(mod.colorGlyphs[gid], outlines, mod.metrics.unitsPerEm);
        const paintOps = (content: string): string[] =>
            content.split('\n').filter(l => l === 'f' || / sh$/.test(l));
        const count = (content: string, op: 'f' | 'sh'): number =>
            paintOps(content).filter(l => (op === 'f' ? l === 'f' : l !== 'f')).length;

        /** `[C0, C1]` of every Type 2 segment of a shading function dict. */
        const segments = (fn: PdfValue): [string, string][] => {
            const d = fn instanceof Map ? fn : null;
            if (!d) return [];
            const subs = d.get('Functions');
            if (Array.isArray(subs)) return subs.flatMap(segments);
            const arr = (v: PdfValue | undefined): string => (Array.isArray(v) ? v.map(String).join(' ') : '');
            return [[arr(d.get('C0')), arr(d.get('C1'))]];
        };
        const isName = (v: PdfValue | undefined, name: string): boolean =>
            typeof v === 'object' && v !== null && 'type' in v && v.type === 'name' && v.value === name;
        /** Every Form XObject of a document: its content and its shading functions. */
        const formsOf = (bytes: Uint8Array): { content: string; functions: [string, string][][] }[] => {
            const doc = openPdf(bytes);
            const out: { content: string; functions: [string, string][][] }[] = [];
            for (const num of doc.xref.entries.keys()) {
                const obj = doc.getObject(num);
                if (!obj || typeof obj !== 'object' || !('type' in obj) || obj.type !== 'stream') continue;
                if (!isName(obj.dict.get('Subtype'), 'Form')) continue;
                const res = obj.dict.get('Resources');
                const shading = res instanceof Map ? res.get('Shading') : undefined;
                const functions: [string, string][][] = [];
                for (const dict of (shading instanceof Map ? shading : new Map<string, PdfValue>()).values()) {
                    functions.push(segments((dict as PdfDict).get('Function') ?? null));
                }
                out.push({ content: Buffer.from(doc.decodeStream(obj)).toString('latin1'), functions });
            }
            return out;
        };

        it('renders WOMAN and its toned form without a flat shading over the face', () => {
            const fontData = colorEmoji as unknown as FontData;
            const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
            const bytes = buildDocumentPDFBytes({
                title: 'Woman',
                blocks: [{ type: 'paragraph', text: '\u{1F469} \u{1F469}\u{1F3FD}' }],
                fontEntries: [entry],
            });
            const forms = formsOf(bytes);
            expect(forms).toHaveLength(2);
            // The `rg` operator of every solid layer of a glyph, as the renderer writes it.
            const ch = (v: number): string => (v / 255).toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
            const fillsOf = (gid: number): string[] => mod.colorGlyphs[gid].layers
                .flatMap(l => (l.paint.kind === 'solid' ? [`${ch(l.paint.color[0])} ${ch(l.paint.color[1])} ${ch(l.paint.color[2])} rg`] : []));
            // U+1F469 is gid 2207; its medium-tone form is gid 501. Face
            // (gid 9938 or its toned twin), mouth (9941) and eyes (5868) are
            // among their solid layers; before the fix the last layer, an
            // alpha-ramp radial (gid 9945), was painted opaque over them all.
            for (const { content, functions } of forms) {
                // No shading whose function is constant across every segment.
                for (const segs of functions) expect(segs.every(([c0, c1]) => c0 === c1)).toBe(false);
                // The last painting op is a solid fill, not a shading.
                const ops = paintOps(content);
                expect(ops[ops.length - 1]).toBe('f');
                // Every solid layer of the glyph is painted after every shading left.
                const lines = content.split('\n');
                const lastSh = lines.reduce((at, l, i) => (/ sh$/.test(l) ? i : at), -1);
                const fills = [fillsOf(2207), fillsOf(501)].find(f => f.every(rgb => lines.includes(rgb)));
                expect(fills, 'form matches neither WOMAN nor its medium-tone form').toBeDefined();
                expect(fills?.length).toBeGreaterThanOrEqual(9);
                for (const rgb of fills ?? []) expect(lines.indexOf(rgb), rgb).toBeGreaterThan(lastSh);
            }
        });

        it('pins the op counts of a shadowed glyph and of an untouched one', () => {
            // U+1F9D1 PERSON: its twelve shadings were all alpha ramps (12 `sh`
            // before the fix); its ten solid fills are what remains.
            const person = render(mod.cmap[0x1F9D1]).content;
            expect(count(person, 'sh')).toBe(0);
            expect(count(person, 'f')).toBe(10);
            // U+1F386 FIREWORKS: 36 gradients whose RGB varies — unchanged.
            const fireworks = render(mod.cmap[0x1F386]);
            expect(count(fireworks.content, 'sh')).toBe(36);
            expect(count(fireworks.content, 'f')).toBe(30);
            expect(fireworks.shadings).toHaveLength(36);
            const layers = mod.colorGlyphs[mod.cmap[0x1F386]].layers;
            expect(layers.some(l => l.paint.kind !== 'solid' && l.paint.kind !== 'sweep' && isAlphaRamp(l.paint.stops))).toBe(false);
        });

        it('classifies WOMAN\'s last layer as an alpha ramp', () => {
            const woman = mod.colorGlyphs[mod.cmap[0x1F469]];
            const last = woman.layers[woman.layers.length - 1];
            expect(last.glyphId).toBe(9945);
            expect(last.paint.kind).toBe('radial');
            expect(last.paint.kind !== 'solid' && last.paint.kind !== 'sweep' && isAlphaRamp(last.paint.stops)).toBe(true);
        });

        // Rendering all 1412 glyphs takes about two seconds bare; more under
        // coverage instrumentation.
        it('emits no constant shading anywhere in the bundled module', { timeout: 60_000 }, () => {
            expect(glyf).not.toBeNull();
            let ramps = 0;
            let forms = 0;
            const constantFn = (dict: string): boolean => {
                const segs = [...dict.matchAll(/\/C0 \[([^\]]*)\] \/C1 \[([^\]]*)\]/g)];
                return segs.length > 0 && segs.every(m => m[1] === m[2]);
            };
            for (const [gid, glyph] of Object.entries(mod.colorGlyphs)) {
                for (const layer of glyph.layers) {
                    const p = layer.paint;
                    if ((p.kind === 'linear' || p.kind === 'radial') && isAlphaRamp(p.stops)) ramps++;
                }
                const form = renderColorGlyph(glyph, outlines, mod.metrics.unitsPerEm);
                forms++;
                for (const s of form.shadings) expect(constantFn(s.dict), `gid ${gid} ${s.name}`).toBe(false);
                const ops = paintOps(form.content);
                if (ops.length > 0 && ops[ops.length - 1] !== 'f') {
                    // A form may still end on a shading — one whose RGB varies.
                    const name = ops[ops.length - 1].replace(/^\/(\w+) sh$/, '$1');
                    const last = form.shadings.find(s => s.name === name);
                    expect(last, `gid ${gid} ends on ${name}`).toBeDefined();
                }
            }
            expect(forms).toBe(Object.keys(mod.colorGlyphs).length);
            // The module carries about a thousand of these layers; the count
            // is a fact of the font, not of the renderer.
            expect(ramps).toBeGreaterThan(900);
        });
    });
});
