import { describe, it, expect } from 'vitest';
import * as colorEmoji from '../../fonts/noto-color-emoji-data.js';
import { buildDocumentPDFBytes } from '../../src/core/pdf-document.js';
import { openPdf } from '../../src/parser/pdf-reader.js';
import type { FontData, FontEntry } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';

// Guards the committed curated colour-emoji data module
// (fonts/noto-color-emoji-data.js, generated by scripts/build-color-emoji-data.ts).

describe('noto-color-emoji-data module', () => {
    it('exports a valid colour FontData shape', () => {
        expect(colorEmoji.fontName).toBe('NotoColorEmoji-Regular');
        expect(typeof colorEmoji.ttfBase64).toBe('string');
        expect(colorEmoji.ttfBase64.length).toBeGreaterThan(1000);
        expect(colorEmoji.metrics.unitsPerEm).toBeGreaterThan(0);
        expect(Object.keys(colorEmoji.colorGlyphs).length).toBeGreaterThan(100);
        expect(Object.keys(colorEmoji.cmap).length).toBeGreaterThan(100);
    });

    it('maps common emoji codepoints to colour glyphs', () => {
        const grin = colorEmoji.cmap[0x1f600];
        expect(grin).toBeGreaterThan(0);
        expect(colorEmoji.colorGlyphs[grin]).toBeDefined();
        expect(colorEmoji.colorGlyphs[grin].layers.length).toBeGreaterThan(0);
    });

    it('renders colour emoji as Form XObjects in a document', () => {
        const fontData = colorEmoji as unknown as FontData;
        const entry: FontEntry = { fontData, fontRef: '/F3', lang: 'emoji' };
        const params: DocumentParams = {
            title: 'Colour Emoji Module',
            blocks: [{ type: 'paragraph', text: 'Hi \u{1F600} \u{2764} \u{1F44D} there' }],
            fontEntries: [entry],
        };
        const bytes = buildDocumentPDFBytes(params);
        const pdf = Buffer.from(bytes).toString('latin1');
        expect(pdf).toContain('/Subtype /Form');
        expect(pdf).toMatch(/\/CEm\d+ Do/);
        const doc = openPdf(bytes);
        expect(doc.pageCount).toBe(1);
    });
});
