import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { generatePDFMainThread, generatePDFInWorker, createPDF, WORKER_THRESHOLD, WORKER_TIMEOUT_MS } from '../../src/worker/worker-api.js';
import type { PdfParams } from '../../src/types/pdf-types.js';

/** Minimal valid PdfParams for testing */
const minimalParams: PdfParams = {
    title: 'Test',
    infoItems: [{ label: 'Account', value: '1234' }],
    balanceText: 'Balance: $100.00',
    countText: '1 item',
    headers: ['Date', 'Description', 'Amount'],
    rows: [{ cells: ['01/01', 'Item A', '$50.00'], type: 'credit', pointed: false }],
    footerText: 'Generated by pdfnative',
};

describe('constants', () => {
    it('should export WORKER_THRESHOLD', () => {
        expect(WORKER_THRESHOLD).toBe(500);
    });

    it('should export WORKER_TIMEOUT_MS', () => {
        expect(WORKER_TIMEOUT_MS).toBe(60000);
    });
});

describe('generatePDFMainThread', () => {
    it('should return a Uint8Array', () => {
        const result = generatePDFMainThread(minimalParams);
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should produce valid PDF header', () => {
        const result = generatePDFMainThread(minimalParams);
        // PDF starts with %PDF-
        const header = String.fromCharCode(...result.slice(0, 5));
        expect(header).toBe('%PDF-');
    });

    it('should accept optional layout options', () => {
        const result = generatePDFMainThread(minimalParams, {});
        expect(result).toBeInstanceOf(Uint8Array);
        expect(result.length).toBeGreaterThan(0);
    });
});

describe('createPDF', () => {
    it('should return Uint8Array for small datasets (main thread)', async () => {
        const result = await createPDF(minimalParams);
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should use main thread when no workerUrl provided', async () => {
        const manyRows = Array.from({ length: 600 }, (_, i) => ({ cells: [`${i}`, `row${i}`, '$0.00'], type: 'credit', pointed: false }));
        const result = await createPDF({ ...minimalParams, rows: manyRows });
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should use main thread when below threshold', async () => {
        const result = await createPDF(minimalParams, { threshold: 1000 });
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should use main thread when Worker is undefined', async () => {
        // In Node.js vitest environment, Worker is not defined
        const manyRows = Array.from({ length: 600 }, (_, i) => ({ cells: [`${i}`, `row${i}`, '$0.00'], type: 'credit', pointed: false }));
        const result = await createPDF(
            { ...minimalParams, rows: manyRows },
            { workerUrl: 'fake.js' }
        );
        expect(result).toBeInstanceOf(Uint8Array);
    });

    it('should produce valid PDF content', async () => {
        const result = await createPDF(minimalParams);
        const header = String.fromCharCode(...result.slice(0, 5));
        expect(header).toBe('%PDF-');
        // Check for EOF marker
        const tail = String.fromCharCode(...result.slice(-5));
        expect(tail).toBe('%%EOF');
    });

    it('should support custom threshold', async () => {
        // Set threshold to 0 so even 1 row triggers "large" path
        // But without Worker global, it falls back to main thread
        const result = await createPDF(minimalParams, { threshold: 0 });
        expect(result).toBeInstanceOf(Uint8Array);
    });
});

describe('generatePDFInWorker', () => {
    let mockWorkerInstance: {
        onmessage: ((e: { data: unknown }) => void) | null;
        onerror: ((e: { message: string }) => void) | null;
        postMessage: ReturnType<typeof vi.fn>;
        terminate: ReturnType<typeof vi.fn>;
    };

    beforeEach(() => {
        mockWorkerInstance = {
            onmessage: null,
            onerror: null,
            postMessage: vi.fn(),
            terminate: vi.fn(),
        };
        vi.stubGlobal('Worker', class {
            onmessage: ((e: { data: unknown }) => void) | null = null;
            onerror: ((e: { message: string }) => void) | null = null;
            postMessage = mockWorkerInstance.postMessage;
            terminate = mockWorkerInstance.terminate;
            constructor() {
                // Capture reference so tests can trigger callbacks
                const self = this;
                mockWorkerInstance.onmessage = (e) => self.onmessage?.(e as MessageEvent);
                mockWorkerInstance.onerror = (e) => self.onerror?.(e as ErrorEvent);
            }
        });
    });

    afterEach(() => {
        vi.unstubAllGlobals();
        vi.restoreAllMocks();
    });

    it('should resolve with pdfBytes on complete message', async () => {
        const pdfBytes = new Uint8Array([0x25, 0x50, 0x44, 0x46]);
        const promise = generatePDFInWorker('worker.js', minimalParams);

        // The Worker constructor is synchronous, callbacks are set after promise microtask
        await new Promise(r => setTimeout(r, 0));
        mockWorkerInstance.onmessage!({ data: { type: 'complete', pdfBytes } });

        const result = await promise;
        expect(result).toBe(pdfBytes);
        expect(mockWorkerInstance.terminate).toHaveBeenCalled();
    });

    it('should call onProgress callback on progress message', async () => {
        const onProgress = vi.fn();
        const promise = generatePDFInWorker('worker.js', minimalParams, onProgress);

        await new Promise(r => setTimeout(r, 0));
        mockWorkerInstance.onmessage!({ data: { type: 'progress', percent: 50 } });
        mockWorkerInstance.onmessage!({ data: { type: 'complete', pdfBytes: new Uint8Array(1) } });

        await promise;
        expect(onProgress).toHaveBeenCalledWith(50);
    });

    it('should reject on error message from worker', async () => {
        const promise = generatePDFInWorker('worker.js', minimalParams);

        await new Promise(r => setTimeout(r, 0));
        mockWorkerInstance.onmessage!({ data: { type: 'error', message: 'Test error' } });

        await expect(promise).rejects.toThrow('Test error');
        expect(mockWorkerInstance.terminate).toHaveBeenCalled();
    });

    it('should reject on worker onerror', async () => {
        const promise = generatePDFInWorker('worker.js', minimalParams);

        await new Promise(r => setTimeout(r, 0));
        mockWorkerInstance.onerror!({ message: 'Script load failed' });

        await expect(promise).rejects.toThrow('Worker error: Script load failed');
    });

    it('should reject on timeout', async () => {
        vi.useFakeTimers();
        const promise = generatePDFInWorker('worker.js', minimalParams);

        // Attach catch handler before advancing timers to avoid unhandled rejection
        let caughtError: Error | null = null;
        const handled = promise.catch(e => { caughtError = e as Error; });

        await vi.advanceTimersByTimeAsync(WORKER_TIMEOUT_MS);
        await handled;

        expect(caughtError).toBeInstanceOf(Error);
        expect(caughtError!.message).toBe('PDF Worker timeout');
        expect(mockWorkerInstance.terminate).toHaveBeenCalled();
        vi.useRealTimers();
    });

    it('should send GENERATE_PDF message to worker', async () => {
        const promise = generatePDFInWorker('worker.js', minimalParams);

        await new Promise(r => setTimeout(r, 0));
        mockWorkerInstance.onmessage!({ data: { type: 'complete', pdfBytes: new Uint8Array(1) } });
        await promise;

        expect(mockWorkerInstance.postMessage).toHaveBeenCalledWith({
            type: 'GENERATE_PDF',
            params: minimalParams,
        });
    });

    it('should reject if Worker constructor throws', async () => {
        vi.stubGlobal('Worker', class {
            constructor() { throw new Error('CSP violation'); }
        });

        await expect(generatePDFInWorker('worker.js', minimalParams)).rejects.toThrow('CSP violation');
    });
});

describe('createPDF with Worker', () => {
    afterEach(() => {
        vi.useRealTimers();
        vi.unstubAllGlobals();
    });

    it('should fall back to main thread when Worker fails', async () => {
        vi.stubGlobal('Worker', class {
            constructor() { throw new Error('Worker unavailable'); }
        });

        const manyRows = Array.from({ length: 600 }, (_, i) => ({
            cells: [`${i}`, `row${i}`, '$0.00'], type: 'credit', pointed: false,
        }));

        const result = await createPDF(
            { ...minimalParams, rows: manyRows },
            { workerUrl: 'worker.js' }
        );

        // Falls back to main thread
        expect(result).toBeInstanceOf(Uint8Array);
        const header = String.fromCharCode(...result.slice(0, 5));
        expect(header).toBe('%PDF-');
    });
});
