/**
 * BUILD COLOUR-EMOJI DATA — Noto Color Emoji (COLR/CPAL) → JS Data Module
 * ========================================================================
 * Regenerates the BUNDLED curated colour-emoji module
 * (`fonts/noto-color-emoji-data.{js,d.ts}`) from NotoColorEmoji-Regular.ttf.
 *
 * The full font (~24 MB, ~3 600 colour glyphs) is intentionally NOT bundled —
 * that would produce a ~32 MB module, violating pdfnative's lean-module
 * philosophy. A focused subset of the most common emoji keeps the module
 * small while covering everyday use.
 *
 * For FULL coverage (or any custom subset), end users run the public CLI
 * shipped with the package — it dogfoods the exact same build core:
 *   npx pdfnative-build-emoji-font --download --all
 *   npx pdfnative-build-emoji-font --ttf NotoColorEmoji-Regular.ttf --codepoints 1F600,1F680
 * (see scripts/build-emoji-font.ts / docs/guides/colour-emoji-cli.md)
 *
 * Usage (maintainers, regenerate the bundled curated module):
 *   npx tsx scripts/build-color-emoji-data.ts
 *
 * Zero external dependency. License: Noto Color Emoji is OFL-1.1.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildEmojiFontModule } from './lib/emoji-font-core.js';
import { CURATED_EMOJI } from './lib/curated-emoji.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const TTF_PATH = join(ROOT, 'fonts', 'ttf', 'NotoColorEmoji-Regular.ttf');
const OUT_JS = join(ROOT, 'fonts', 'noto-color-emoji-data.js');
const OUT_DTS = join(ROOT, 'fonts', 'noto-color-emoji-data.d.ts');

function main(): void {
    const ttf = new Uint8Array(readFileSync(TTF_PATH));

    const { js, dts, stats } = buildEmojiFontModule(ttf, CURATED_EMOJI, {
        fontName: 'NotoColorEmoji-Regular',
        dtsTypeImport: '../src/types/pdf-types.js',
        makeBanner: (kept) => `/**
 * PRE-BUILT COLOUR-EMOJI FONT DATA — NotoColorEmoji-Regular (curated subset)
 * ==========================================================================
 * Generated by: scripts/build-color-emoji-data.ts
 * Source: NotoColorEmoji-Regular.ttf (OFL-1.1)
 * Colour glyphs: ${kept} (curated). COLR/CPAL → solid + linear + radial paints.
 *
 * Opt in:
 *   import { registerFont } from 'pdfnative';
 *   registerFont('emoji', () => import('pdfnative/fonts/noto-color-emoji-data.js'));
 *
 * DO NOT EDIT — regenerate with: npx tsx scripts/build-color-emoji-data.ts
 */`,
    });

    // Hard size guard: the bundled module ships in every npm install, so keep
    // it within the ~4 MB budget (the full ~3 600-glyph set is ~32 MB and is
    // intentionally left to the CLI). Trim the curated list if this trips.
    const MAX_SIZE_KB = 4096;
    if (stats.sizeKb > MAX_SIZE_KB) {
        throw new Error(
            `curated colour-emoji module is ${stats.sizeKb} KB, over the ${MAX_SIZE_KB} KB budget — ` +
            'trim scripts/lib/curated-emoji.ts',
        );
    }

    writeFileSync(OUT_JS, js);
    writeFileSync(OUT_DTS, dts);

    console.log(`Colour-emoji data module written:`);
    console.log(`  curated glyphs kept: ${stats.kept}  (missing: ${stats.missing})`);
    console.log(`  used gids (outlines+CIDs): ${stats.usedGids}`);
    console.log(`  module size: ${stats.sizeKb} KB (budget ${MAX_SIZE_KB} KB)`);
    console.log(`  ${OUT_JS}`);
}

main();
