/**
 * pdfnative — Parser Tests
 * ==========================
 * Tests for PDF inflate, tokenizer, object parser, xref parser, reader, and modifier.
 * Includes round-trip tests: generate → parse → verify.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
    inflateSync, setInflateImpl, initNodeDecompression as initNodeDecompression_parser,
} from '../../src/parser/pdf-inflate.js';
import {
    createTokenizer,
} from '../../src/parser/pdf-tokenizer.js';
import type { PdfToken } from '../../src/parser/pdf-tokenizer.js';
import {
    parseValue, parseIndirectObject,
    isRef, isName, isStream, isDict, isArray,
    dictGet, dictGetName, dictGetNum, dictGetRef, dictGetDict, dictGetArray,
} from '../../src/parser/pdf-object-parser.js';
import type { PdfValue, PdfName, PdfDict, PdfRef, PdfStream } from '../../src/parser/pdf-object-parser.js';
import {
    findStartxref, parseXrefTable,
    getTrailerValue, getTrailerRef,
} from '../../src/parser/pdf-xref-parser.js';
import type { XrefTable } from '../../src/parser/pdf-xref-parser.js';
import {
    openPdf,
} from '../../src/parser/pdf-reader.js';
import type { PdfReader } from '../../src/parser/pdf-reader.js';
import {
    createModifier,
} from '../../src/parser/pdf-modifier.js';
import {
    buildPDFBytes,
} from '../../src/core/pdf-builder.js';
import {
    buildDocumentPDFBytes,
} from '../../src/core/pdf-document.js';
import {
    initNodeCompression, deflateSync,
} from '../../src/core/pdf-compress.js';
import type { PdfParams } from '../../src/types/pdf-types.js';
import type { DocumentParams } from '../../src/types/pdf-document-types.js';

// ── Helpers ──────────────────────────────────────────────────────────

function textEncoder(str: string): Uint8Array {
    const arr = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) arr[i] = str.charCodeAt(i);
    return arr;
}

function minimalTableParams(): PdfParams {
    return {
        title: 'Test Report',
        infoItems: [{ label: 'Period', value: 'Jan 2026' }],
        balanceText: 'Balance: $100.00',
        countText: '2 items',
        headers: ['Date', 'Description', 'Amount'],
        rows: [
            { cells: ['01/01', 'Item A', '$50.00'], type: 'credit', pointed: false },
            { cells: ['01/02', 'Item B', '-$25.00'], type: 'debit', pointed: true },
        ],
        footerText: 'Generated by pdfnative',
    };
}

function minimalDocumentParams(): DocumentParams {
    return {
        title: 'Test Document',
        blocks: [
            { type: 'heading', text: 'Chapter One', level: 1 },
            { type: 'paragraph', text: 'Lorem ipsum dolor sit amet.' },
            { type: 'heading', text: 'Section Two', level: 2 },
            { type: 'paragraph', text: 'Second paragraph of test content.' },
        ],
        footerText: 'Generated by pdfnative',
    };
}

function collectTokens(src: string): PdfToken[] {
    const tok = createTokenizer(textEncoder(src));
    const tokens: PdfToken[] = [];
    let t: PdfToken | null;
    while ((t = tok.next()) !== null) tokens.push(t);
    return tokens;
}

// ── Initialize ───────────────────────────────────────────────────────

beforeAll(async () => {
    await initNodeCompression();
    await initNodeDecompression_parser();
});

// ═════════════════════════════════════════════════════════════════════
// INFLATE TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-inflate', () => {
    it('round-trips with deflateSync', () => {
        const original = textEncoder('Hello, PDF inflate round-trip test!');
        const compressed = deflateSync(original);
        const decompressed = inflateSync(compressed);
        expect(decompressed).toEqual(original);
    });

    it('round-trips empty data', () => {
        const original = new Uint8Array(0);
        const compressed = deflateSync(original);
        const decompressed = inflateSync(compressed);
        expect(decompressed.length).toBe(0);
    });

    it('round-trips large data', () => {
        const original = new Uint8Array(10000);
        for (let i = 0; i < original.length; i++) original[i] = i & 0xFF;
        const compressed = deflateSync(original);
        const decompressed = inflateSync(compressed);
        expect(decompressed).toEqual(original);
    });

    it('round-trips repetitive data (good compression)', () => {
        const original = new Uint8Array(5000);
        for (let i = 0; i < original.length; i++) original[i] = 0x41; // 'A'
        const compressed = deflateSync(original);
        expect(compressed.length).toBeLessThan(original.length);
        const decompressed = inflateSync(compressed);
        expect(decompressed).toEqual(original);
    });

    it('works with pure JS implementation (setInflateImpl)', async () => {
        // Temporarily disable native
        const original = textEncoder('Pure JS inflate test');
        const compressed = deflateSync(original);

        setInflateImpl(null);
        const decompressed = inflateSync(compressed);
        expect(decompressed).toEqual(original);

        // Restore native
        await initNodeDecompression_parser();
    });

    it('throws on invalid data', () => {
        expect(() => inflateSync(new Uint8Array([0, 1, 2, 3]))).toThrow();
    });
});

// ═════════════════════════════════════════════════════════════════════
// TOKENIZER TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-tokenizer', () => {
    describe('numbers', () => {
        it('parses integers', () => {
            const tokens = collectTokens('0 42 -7 12345');
            expect(tokens.map(t => t.value)).toEqual([0, 42, -7, 12345]);
            expect(tokens.every(t => t.type === 'number')).toBe(true);
        });

        it('parses real numbers', () => {
            const tokens = collectTokens('3.14 -0.5 .25 100.');
            expect(tokens.map(t => t.value)).toEqual([3.14, -0.5, 0.25, 100]);
        });
    });

    describe('strings', () => {
        it('parses literal strings', () => {
            const tokens = collectTokens('(Hello World)');
            expect(tokens).toHaveLength(1);
            expect(tokens[0].type).toBe('string');
            expect(tokens[0].value).toBe('Hello World');
        });

        it('handles escape sequences', () => {
            const tokens = collectTokens('(line1\\nline2)');
            expect(tokens[0].value).toBe('line1\nline2');
        });

        it('handles nested parentheses', () => {
            const tokens = collectTokens('(text (nested) more)');
            expect(tokens[0].value).toBe('text (nested) more');
        });

        it('handles escaped parentheses', () => {
            const tokens = collectTokens('(escaped \\( paren \\))');
            expect(tokens[0].value).toBe('escaped ( paren )');
        });

        it('handles octal escapes', () => {
            const tokens = collectTokens('(\\101)'); // 'A' = 0o101 = 65
            expect(tokens[0].value).toBe('A');
        });

        it('parses hex strings', () => {
            const tokens = collectTokens('<48656C6C6F>');
            expect(tokens[0].type).toBe('string');
            expect(tokens[0].value).toBe('Hello');
        });

        it('handles odd-length hex strings (padding)', () => {
            const tokens = collectTokens('<ABC>');
            expect(tokens[0].type).toBe('string');
            // 0xAB, 0xC0
            expect(tokens[0].value).toBe('\xAB\xC0');
        });
    });

    describe('names', () => {
        it('parses simple names', () => {
            const tokens = collectTokens('/Type /Catalog /Pages');
            expect(tokens.map(t => t.value)).toEqual(['Type', 'Catalog', 'Pages']);
            expect(tokens.every(t => t.type === 'name')).toBe(true);
        });

        it('handles #XX escapes in names', () => {
            const tokens = collectTokens('/A#20B');
            expect(tokens[0].value).toBe('A B');
        });
    });

    describe('keywords', () => {
        it('parses boolean and null keywords', () => {
            const tokens = collectTokens('true false null');
            expect(tokens.map(t => ({ type: t.type, value: t.value }))).toEqual([
                { type: 'keyword', value: 'true' },
                { type: 'keyword', value: 'false' },
                { type: 'keyword', value: 'null' },
            ]);
        });

        it('parses obj/endobj keywords', () => {
            const tokens = collectTokens('obj endobj');
            expect(tokens.map(t => t.value)).toEqual(['obj', 'endobj']);
        });

        it('parses stream/endstream keywords', () => {
            const tokens = collectTokens('stream endstream');
            expect(tokens.map(t => t.value)).toEqual(['stream', 'endstream']);
        });

        it('parses xref and trailer keywords', () => {
            const tokens = collectTokens('xref trailer startxref');
            expect(tokens.map(t => t.value)).toEqual(['xref', 'trailer', 'startxref']);
        });
    });

    describe('delimiters', () => {
        it('parses array delimiters', () => {
            const tokens = collectTokens('[ 1 2 3 ]');
            expect(tokens[0].type).toBe('arrayOpen');
            expect(tokens[4].type).toBe('arrayClose');
        });

        it('parses dictionary delimiters', () => {
            const tokens = collectTokens('<< /Type /Catalog >>');
            expect(tokens[0].type).toBe('dictOpen');
            expect(tokens[3].type).toBe('dictClose');
        });
    });

    describe('comments', () => {
        it('skips comments', () => {
            const tokens = collectTokens('42 %this is a comment\n99');
            expect(tokens.map(t => t.value)).toEqual([42, 99]);
        });
    });

    describe('whitespace', () => {
        it('handles various whitespace characters', () => {
            const tokens = collectTokens('1\t2\r\n3');
            expect(tokens.map(t => t.value)).toEqual([1, 2, 3]);
        });
    });

    describe('peek', () => {
        it('peek does not consume token', () => {
            const tok = createTokenizer(textEncoder('42 99'));
            const p = tok.peek();
            expect(p?.value).toBe(42);
            const t = tok.next();
            expect(t?.value).toBe(42);
        });
    });
});

// ═════════════════════════════════════════════════════════════════════
// OBJECT PARSER TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-object-parser', () => {
    function parse(src: string): PdfValue {
        const tok = createTokenizer(textEncoder(src));
        return parseValue(tok);
    }

    describe('primitives', () => {
        it('parses null', () => {
            expect(parse('null')).toBeNull();
        });

        it('parses booleans', () => {
            expect(parse('true')).toBe(true);
            expect(parse('false')).toBe(false);
        });

        it('parses integers', () => {
            expect(parse('42')).toBe(42);
            expect(parse('-7')).toBe(-7);
        });

        it('parses real numbers', () => {
            expect(parse('3.14')).toBeCloseTo(3.14);
        });

        it('parses names', () => {
            const val = parse('/Type');
            expect(isName(val)).toBe(true);
            expect((val as PdfName).value).toBe('Type');
        });

        it('parses strings', () => {
            expect(parse('(Hello)')).toBe('Hello');
        });
    });

    describe('indirect references', () => {
        it('parses "N G R" as indirect ref', () => {
            const val = parse('5 0 R');
            expect(isRef(val)).toBe(true);
            const ref = val as PdfRef;
            expect(ref.num).toBe(5);
            expect(ref.gen).toBe(0);
        });

        it('does not confuse two numbers with non-R', () => {
            const tok = createTokenizer(textEncoder('5 0'));
            const val = parseValue(tok);
            expect(val).toBe(5);
        });
    });

    describe('arrays', () => {
        it('parses empty array', () => {
            const val = parse('[ ]');
            expect(isArray(val)).toBe(true);
            expect(val).toHaveLength(0);
        });

        it('parses array with mixed types', () => {
            const val = parse('[1 /Name (string) true null]');
            expect(isArray(val)).toBe(true);
            const arr = val as PdfValue[];
            expect(arr).toEqual([1, { type: 'name', value: 'Name' }, 'string', true, null]);
        });

        it('parses nested arrays', () => {
            const val = parse('[[1 2] [3 4]]');
            expect(isArray(val)).toBe(true);
            const arr = val as PdfValue[];
            expect(arr).toHaveLength(2);
            expect(arr[0]).toEqual([1, 2]);
        });

        it('parses array with refs', () => {
            const val = parse('[1 0 R 2 0 R]');
            expect(isArray(val)).toBe(true);
            const arr = val as PdfValue[];
            expect(arr).toHaveLength(2);
            expect(isRef(arr[0])).toBe(true);
            expect((arr[0] as PdfRef).num).toBe(1);
        });
    });

    describe('dictionaries', () => {
        it('parses empty dict', () => {
            const val = parse('<< >>');
            expect(isDict(val)).toBe(true);
            expect((val as PdfDict).size).toBe(0);
        });

        it('parses dict with entries', () => {
            const val = parse('<< /Type /Catalog /Pages 3 0 R >>');
            expect(isDict(val)).toBe(true);
            const dict = val as PdfDict;
            expect(dictGetName(dict, 'Type')).toBe('Catalog');
            expect(isRef(dict.get('Pages')!)).toBe(true);
        });

        it('parses nested dicts', () => {
            const val = parse('<< /Font << /F1 5 0 R >> >>');
            expect(isDict(val)).toBe(true);
            const dict = val as PdfDict;
            const font = dictGetDict(dict, 'Font');
            expect(font).toBeDefined();
            expect(isRef(font!.get('F1')!)).toBe(true);
        });

        it('parses dict with array values', () => {
            const val = parse('<< /Kids [1 0 R 2 0 R] /Count 2 >>');
            expect(isDict(val)).toBe(true);
            const dict = val as PdfDict;
            const kids = dictGetArray(dict, 'Kids');
            expect(kids).toHaveLength(2);
            expect(dictGetNum(dict, 'Count')).toBe(2);
        });
    });

    describe('indirect objects', () => {
        it('parses indirect object definition', () => {
            const tok = createTokenizer(textEncoder('1 0 obj\n<< /Type /Catalog >>\nendobj'));
            const obj = parseIndirectObject(tok);
            expect(obj).not.toBeNull();
            expect(obj!.num).toBe(1);
            expect(obj!.gen).toBe(0);
            expect(isDict(obj!.value)).toBe(true);
        });

        it('parses indirect object with number value', () => {
            const tok = createTokenizer(textEncoder('7 0 obj\n42\nendobj'));
            const obj = parseIndirectObject(tok);
            expect(obj!.num).toBe(7);
            expect(obj!.value).toBe(42);
        });

        it('parses indirect object with string value', () => {
            const tok = createTokenizer(textEncoder('3 0 obj\n(Hello World)\nendobj'));
            const obj = parseIndirectObject(tok);
            expect(obj!.value).toBe('Hello World');
        });
    });

    describe('streams', () => {
        it('parses stream object with /Length', () => {
            const content = 'BT /F1 12 Tf (Hello) Tj ET';
            const src = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
            const tok = createTokenizer(textEncoder(src));
            const val = parseValue(tok);
            expect(isStream(val)).toBe(true);
            const stream = val as PdfStream;
            expect(stream.data.length).toBe(content.length);
        });
    });

    describe('dict helpers', () => {
        it('dictGet returns undefined for missing keys', () => {
            const dict: PdfDict = new Map();
            expect(dictGet(dict, 'Missing')).toBeUndefined();
        });

        it('dictGetRef returns PdfRef or undefined', () => {
            const dict: PdfDict = new Map();
            dict.set('Ref', { type: 'ref' as const, num: 1, gen: 0 });
            dict.set('Num', 42);
            expect(dictGetRef(dict, 'Ref')).toEqual({ type: 'ref', num: 1, gen: 0 });
            expect(dictGetRef(dict, 'Num')).toBeUndefined();
        });
    });

    describe('isRef/isStream/isDict/isArray guards', () => {
        it('isRef correctly identifies refs', () => {
            expect(isRef({ type: 'ref', num: 1, gen: 0 })).toBe(true);
            expect(isRef(null)).toBe(false);
            expect(isRef(42)).toBe(false);
            expect(isRef('string')).toBe(false);
        });

        it('isStream correctly identifies streams', () => {
            expect(isStream({ type: 'stream', dict: new Map(), data: new Uint8Array() })).toBe(true);
            expect(isStream(null)).toBe(false);
        });

        it('isDict correctly identifies Map dictionaries', () => {
            expect(isDict(new Map())).toBe(true);
            expect(isDict({} as unknown as PdfValue)).toBe(false);
            expect(isDict(null)).toBe(false);
        });

        it('isArray correctly identifies arrays', () => {
            expect(isArray([1, 2, 3])).toBe(true);
            expect(isArray(null)).toBe(false);
            expect(isArray('not array')).toBe(false);
        });
    });
});

// ═════════════════════════════════════════════════════════════════════
// XREF PARSER TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-xref-parser', () => {
    describe('findStartxref', () => {
        it('finds startxref at end of file', () => {
            const pdf = textEncoder('%PDF-1.4\nstartxref\n12345\n%%EOF\n');
            expect(findStartxref(pdf)).toBe(12345);
        });

        it('throws when startxref missing', () => {
            const pdf = textEncoder('%PDF-1.4\n%%EOF\n');
            expect(() => findStartxref(pdf)).toThrow('startxref not found');
        });
    });

    describe('parseXrefTable — generated PDF', () => {
        let pdfBytes: Uint8Array;
        let xref: XrefTable;

        beforeAll(() => {
            pdfBytes = buildPDFBytes(minimalTableParams(), { compress: false });
            xref = parseXrefTable(pdfBytes);
        });

        it('has entries', () => {
            expect(xref.entries.size).toBeGreaterThan(0);
        });

        it('has object 0 (free head)', () => {
            const entry = xref.entries.get(0);
            expect(entry).toBeDefined();
            expect(entry!.type).toBe(0);
        });

        it('has in-use objects (type 1)', () => {
            let inUseCount = 0;
            for (const entry of xref.entries.values()) {
                if (entry.type === 1) inUseCount++;
            }
            expect(inUseCount).toBeGreaterThan(0);
        });

        it('trailer has /Root', () => {
            const root = getTrailerRef(xref.trailer, 'Root');
            expect(root).toBeDefined();
            expect(root!.num).toBeGreaterThan(0);
        });

        it('trailer has /Size matching entries', () => {
            const size = getTrailerValue(xref.trailer, 'Size');
            expect(typeof size).toBe('number');
            expect(size).toBe(xref.entries.size);
        });
    });
});

// ═════════════════════════════════════════════════════════════════════
// READER TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-reader', () => {
    describe('table-based PDF', () => {
        let pdfBytes: Uint8Array;
        let reader: PdfReader;

        beforeAll(() => {
            pdfBytes = buildPDFBytes(minimalTableParams(), { compress: false });
            reader = openPdf(pdfBytes);
        });

        it('opens PDF without error', () => {
            expect(reader).toBeDefined();
        });

        it('has at least 1 page', () => {
            expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        });

        it('getPage returns a dict', () => {
            const page = reader.getPage(0);
            expect(isDict(page)).toBe(true);
        });

        it('page has /Type /Page', () => {
            const page = reader.getPage(0);
            expect(dictGetName(page, 'Type')).toBe('Page');
        });

        it('page has /MediaBox', () => {
            const page = reader.getPage(0);
            const mediaBox = page.get('MediaBox');
            expect(isArray(mediaBox!)).toBe(true);
        });

        it('page MediaBox matches A4 dimensions', () => {
            const page = reader.getPage(0);
            const mediaBox = page.get('MediaBox') as number[];
            // A4: 595.28 x 841.89
            expect(mediaBox[0]).toBe(0);
            expect(mediaBox[1]).toBe(0);
            expect(mediaBox[2]).toBeCloseTo(595.28, 0);
            expect(mediaBox[3]).toBeCloseTo(841.89, 0);
        });

        it('getCatalog returns dict with /Type /Catalog', () => {
            const catalog = reader.getCatalog();
            expect(dictGetName(catalog, 'Type')).toBe('Catalog');
        });

        it('getInfo returns the info dictionary', () => {
            const info = reader.getInfo();
            // Our PDFs have /Info with /Title etc.
            expect(info).not.toBeNull();
            if (info) {
                expect(info.get('Title')).toBe('Test Report');
            }
        });

        it('throws for out-of-range page index', () => {
            expect(() => reader.getPage(-1)).toThrow();
            expect(() => reader.getPage(999)).toThrow();
        });

        it('getPages returns all pages', () => {
            const pages = reader.getPages();
            expect(pages.length).toBe(reader.pageCount);
        });

        it('resolve returns null for free objects', () => {
            // Object 0 is always free
            const val = reader.resolve({ type: 'ref', num: 0, gen: 65535 });
            expect(val).toBeNull();
        });

        it('getObject returns value for valid object numbers', () => {
            // Object 1 should be the catalog
            const val = reader.getObject(1);
            expect(val).not.toBeNull();
        });

        it('resolveValue passes through primitives', () => {
            expect(reader.resolveValue(42)).toBe(42);
            expect(reader.resolveValue('hello')).toBe('hello');
            expect(reader.resolveValue(null)).toBeNull();
        });
    });

    describe('document-based PDF', () => {
        let pdfBytes: Uint8Array;
        let reader: PdfReader;

        beforeAll(() => {
            pdfBytes = buildDocumentPDFBytes(minimalDocumentParams(), { compress: false });
            reader = openPdf(pdfBytes);
        });

        it('opens document PDF', () => {
            expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        });

        it('document PDF has /Title in info dict', () => {
            const info = reader.getInfo();
            expect(info).not.toBeNull();
            expect(info!.get('Title')).toBe('Test Document');
        });

        it('has catalog with /Pages', () => {
            const catalog = reader.getCatalog();
            expect(catalog.get('Pages')).toBeDefined();
        });
    });

    describe('compressed PDF', () => {
        let pdfBytes: Uint8Array;
        let reader: PdfReader;

        beforeAll(() => {
            pdfBytes = buildPDFBytes(minimalTableParams(), { compress: true });
            reader = openPdf(pdfBytes);
        });

        it('opens compressed PDF', () => {
            expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        });

        it('reads page structure from compressed PDF', () => {
            const page = reader.getPage(0);
            expect(dictGetName(page, 'Type')).toBe('Page');
        });
    });

    describe('multi-page PDF', () => {
        let reader: PdfReader;

        beforeAll(() => {
            // Generate a PDF with enough rows to span multiple pages
            const rows = Array.from({ length: 200 }, (_, i) => ({
                cells: [`Row ${i}`, `Description ${i}`, `$${i * 10}`],
                type: i % 2 === 0 ? 'credit' as const : 'debit' as const,
                pointed: false,
            }));
            const params: PdfParams = {
                ...minimalTableParams(),
                rows,
            };
            const pdfBytes = buildPDFBytes(params, { compress: false });
            reader = openPdf(pdfBytes);
        });

        it('has multiple pages', () => {
            expect(reader.pageCount).toBeGreaterThan(1);
        });

        it('all pages have /Type /Page', () => {
            for (let i = 0; i < reader.pageCount; i++) {
                const page = reader.getPage(i);
                expect(dictGetName(page, 'Type')).toBe('Page');
            }
        });
    });
});

// ═════════════════════════════════════════════════════════════════════
// MODIFIER TESTS
// ═════════════════════════════════════════════════════════════════════

describe('pdf-modifier', () => {
    let originalBytes: Uint8Array;
    let reader: PdfReader;

    beforeAll(() => {
        originalBytes = buildPDFBytes(minimalTableParams(), { compress: false });
        reader = openPdf(originalBytes);
    });

    it('creates a modifier from reader', () => {
        const mod = createModifier(reader);
        expect(mod.reader).toBe(reader);
    });

    it('save returns original when no modifications', () => {
        const mod = createModifier(reader);
        const saved = mod.save();
        expect(saved).toBe(originalBytes); // Same reference, no copy
    });

    it('addObject allocates a new object number', () => {
        const mod = createModifier(reader);
        const num = mod.addObject(42);
        expect(num).toBeGreaterThan(0);
        expect(mod.getObject(num)).toBe(42);
    });

    it('setObject overrides an existing object', () => {
        const mod = createModifier(reader);
        const originalVal = mod.getObject(1);
        mod.setObject(1, 'replaced');
        expect(mod.getObject(1)).toBe('replaced');
        expect(originalVal).not.toBe('replaced');
    });

    it('save with modifications produces valid PDF', () => {
        const mod = createModifier(reader);

        // Add a new info dict entry
        const newDict: PdfDict = new Map();
        newDict.set('Type', 'Custom');
        newDict.set('Value', 42);
        mod.addObject(newDict);

        const saved = mod.save();

        // Modified should be larger
        expect(saved.length).toBeGreaterThan(originalBytes.length);

        // Should start with original content
        for (let i = 0; i < originalBytes.length; i++) {
            expect(saved[i]).toBe(originalBytes[i]);
        }

        // Should contain new xref and trailer
        const tail = new TextDecoder('latin1').decode(saved.subarray(originalBytes.length));
        expect(tail).toContain('xref');
        expect(tail).toContain('trailer');
        expect(tail).toContain('startxref');
        expect(tail).toContain('%%EOF');
        expect(tail).toContain('/Prev');
    });

    it('modified PDF is re-parseable', () => {
        const mod = createModifier(reader);
        const newDict: PdfDict = new Map();
        newDict.set('Custom', 'test-value');
        const objNum = mod.addObject(newDict);

        const saved = mod.save();
        const reader2 = openPdf(saved);

        // Should still have the same pages
        expect(reader2.pageCount).toBe(reader.pageCount);

        // Should be able to resolve the new object
        const obj = reader2.getObject(objNum);
        expect(isDict(obj)).toBe(true);
        if (isDict(obj)) {
            expect(obj.get('Custom')).toBe('test-value');
        }
    });

    it('nextObjNum tracks correctly', () => {
        const mod = createModifier(reader);
        const start = mod.nextObjNum;
        mod.addObject('obj1');
        expect(mod.nextObjNum).toBe(start + 1);
        mod.addObject('obj2');
        expect(mod.nextObjNum).toBe(start + 2);
    });

    it('getObject returns original for unmodified objects', () => {
        const mod = createModifier(reader);
        const val = mod.getObject(1); // catalog
        expect(val).not.toBeNull();
        expect(isDict(val)).toBe(true);
    });

    it('getObject returns null for non-existent objects', () => {
        const mod = createModifier(reader);
        expect(mod.getObject(99999)).toBeNull();
    });

    it('modified PDF round-trips through multiple modifications', () => {
        const mod1 = createModifier(reader);
        mod1.addObject('first-mod');
        const saved1 = mod1.save();

        const reader2 = openPdf(saved1);
        const mod2 = createModifier(reader2);
        mod2.addObject('second-mod');
        const saved2 = mod2.save();

        const reader3 = openPdf(saved2);
        expect(reader3.pageCount).toBe(reader.pageCount);
    });
});

// ═════════════════════════════════════════════════════════════════════
// ROUND-TRIP INTEGRATION TESTS
// ═════════════════════════════════════════════════════════════════════

describe('round-trip integration', () => {
    it('generate table PDF → parse → verify structure', () => {
        const bytes = buildPDFBytes(minimalTableParams(), { compress: false });
        const reader = openPdf(bytes);

        expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        const catalog = reader.getCatalog();
        expect(dictGetName(catalog, 'Type')).toBe('Catalog');
        const info = reader.getInfo();
        expect(info).not.toBeNull();
    });

    it('generate document PDF → parse → verify structure', () => {
        const bytes = buildDocumentPDFBytes(minimalDocumentParams(), { compress: false });
        const reader = openPdf(bytes);

        expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        const catalog = reader.getCatalog();
        expect(dictGetName(catalog, 'Type')).toBe('Catalog');
    });

    it('generate → parse → modify → re-parse', () => {
        const bytes = buildPDFBytes(minimalTableParams(), { compress: false });
        const reader = openPdf(bytes);
        const mod = createModifier(reader);

        // Add a custom annotation dict
        const annot: PdfDict = new Map();
        annot.set('Type', { type: 'name', value: 'Annot' } as PdfName);
        annot.set('Subtype', { type: 'name', value: 'Text' } as PdfName);
        annot.set('Contents', 'Test annotation');
        const annotNum = mod.addObject(annot);

        const modified = mod.save();
        const reader2 = openPdf(modified);

        // Verify the annotation was preserved
        const resolvedAnnot = reader2.getObject(annotNum);
        expect(isDict(resolvedAnnot)).toBe(true);
        if (isDict(resolvedAnnot)) {
            expect(dictGetName(resolvedAnnot, 'Subtype')).toBe('Text');
            expect(resolvedAnnot.get('Contents')).toBe('Test annotation');
        }
    });

    it('compressed PDF round-trip', () => {
        const bytes = buildPDFBytes(minimalTableParams(), { compress: true });
        const reader = openPdf(bytes);

        // Basic structure should still be parseable
        expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        expect(dictGetName(reader.getCatalog(), 'Type')).toBe('Catalog');
    });

    it('document PDF with multiple block types → parse', () => {
        const params: DocumentParams = {
            title: 'Complex Document',
            blocks: [
                { type: 'heading', text: 'Title', level: 1 },
                { type: 'paragraph', text: 'Introduction paragraph.' },
                { type: 'list', items: ['Item 1', 'Item 2', 'Item 3'], style: 'bullet' },
                { type: 'spacer', height: 20 },
                { type: 'heading', text: 'Section 2', level: 2 },
                { type: 'paragraph', text: 'More content here.' },
            ],
            footerText: 'Test footer',
        };
        const bytes = buildDocumentPDFBytes(params, { compress: false });
        const reader = openPdf(bytes);

        expect(reader.pageCount).toBeGreaterThanOrEqual(1);
        const info = reader.getInfo();
        expect(info).not.toBeNull();
        expect(info!.get('Title')).toBe('Complex Document');
    });
});
