/**
 * pdfnative — Pure Native PDF Generation Library
 * =================================================
 * Zero-dependency PDF generation for Node.js and browsers.
 * ISO 32000-1 (PDF 1.7) compliant output.
 *
 * Features:
 *   - Pure JavaScript, no vendor dependencies
 *   - A4 table-based PDF with headers, data rows, pagination
 *   - Free-form document builder (headings, paragraphs, lists, tables, images, links, barcodes)
 *   - Built-in Helvetica (Latin/WinAnsi) — no font embedding needed
 *   - CIDFont Type2/Identity-H embedding for Unicode scripts
 *   - 16 Unicode scripts: Thai, Japanese, Chinese, Korean, Greek, Devanagari, Turkish, Vietnamese, Polish, Arabic, Hebrew, Cyrillic, Georgian, Armenian, Bengali, Tamil
 *   - Thai OpenType shaping (GSUB + GPOS)
 *   - Arabic positional shaping (GSUB isolated/initial/medial/final forms)
 *   - BiDi text layout (simplified UAX #9) with glyph mirroring
 *   - Multi-font cross-script fallback
 *   - TTF font subsetting (dramatic size reduction)
 *   - Tagged PDF / PDF/A-2b (structure tree, /ActualText, XMP metadata, sRGB OutputIntent)
 *   - PDF Encryption (AES-128 / AES-256, owner + user passwords, granular permissions)
 *   - Image embedding (JPEG DCTDecode, PNG FlateDecode)
 *   - Hyperlinks (PDF link annotations with URL validation)
 *   - Barcode & QR code generation (Code 128, EAN-13, QR, Data Matrix, PDF417)
 *   - Web Worker support for large datasets
 *   - Tree-shakeable ESM + CJS dual build
 *
 * @example
 * ```ts
 * import { buildPDFBytes, downloadBlob } from 'pdfnative';
 *
 * const pdf = buildPDFBytes({
 *   title: 'Monthly Report',
 *   infoItems: [{ label: 'Period', value: 'January 2026' }],
 *   balanceText: 'Balance: $1,234.56',
 *   countText: '42 transactions',
 *   headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
 *   rows: [
 *     { cells: ['01/15', 'Grocery Store', 'Food', '-$45.00', ''], type: 'debit', pointed: false },
 *     { cells: ['01/16', 'Salary', 'Income', '+$3,000.00', 'X'], type: 'credit', pointed: true },
 *   ],
 *   footerText: 'Generated by MyApp',
 * });
 *
 * downloadBlob(pdf, 'report.pdf');
 * ```
 *
 * @packageDocumentation
 */

// ── Types ────────────────────────────────────────────────────────────
export type {
    FontMetrics,
    FontData,
    FontEntry,
    ShapedGlyph,
    TextRun,
    EncodingContext,
    PdfRow,
    PdfInfoItem,
    PdfParams,
    PdfColors,
    PdfColor,
    PdfRgbString,
    PdfRgbTuple,
    ColumnDef,
    PdfLayoutOptions,
    EncryptionOptions,
    PageTemplate,
    WatermarkText,
    WatermarkImage,
    WatermarkOptions,
    PdfAttachmentRelationship,
    PdfAttachment,
    WorkerInputMessage,
    WorkerOutputMessage,
} from './types/pdf-types.js';

export type {
    HeadingBlock,
    ParagraphBlock,
    TableBlock,
    ListBlock,
    SpacerBlock,
    PageBreakBlock,
    ImageBlock,
    LinkBlock,
    TocBlock,
    BarcodeBlock,
    SvgBlock,
    FormFieldBlock,
    DocumentBlock,
    DocumentMetadata,
    DocumentParams,
} from './types/pdf-document-types.js';

// ── Core — PDF Builder ──────────────────────────────────────────────
export { buildPDF, buildPDFBytes } from './core/pdf-builder.js';

// ── Core — Document Builder ─────────────────────────────────────────
export { buildDocumentPDF, buildDocumentPDFBytes, wrapText } from './core/pdf-document.js';

// ── Core — Image Support ────────────────────────────────────────────
export type { ParsedImage } from './core/pdf-image.js';
export {
    detectImageFormat, parseJPEG, parsePNG, parseImage,
    buildImageXObject, buildSMaskXObject, buildImageOperators,
} from './core/pdf-image.js';

// ── Core — Link Annotations ─────────────────────────────────────────
export type { LinkAnnotation, InternalLink, Annotation } from './core/pdf-annot.js';
export { validateURL, buildLinkAnnotation, buildInternalLinkAnnotation, isLinkAnnotation } from './core/pdf-annot.js';

// ── Core — Color Utilities ──────────────────────────────────────────
export { parseColor, isValidPdfRgb, normalizeColors } from './core/pdf-color.js';

// ── Core — Watermark ────────────────────────────────────────────────
export type { WatermarkState } from './core/pdf-watermark.js';
export { validateWatermark, buildWatermarkState } from './core/pdf-watermark.js';

// ── Core — Tagged PDF / PDF/A ───────────────────────────────────────
export type { PdfAConfig, EmbeddedFilesResult } from './core/pdf-tags.js';
export { resolvePdfAConfig, buildEmbeddedFiles, validateAttachments } from './core/pdf-tags.js';

// ── Core — Stream Compression ───────────────────────────────────────
export { initNodeCompression, setDeflateImpl } from './core/pdf-compress.js';

// ── Core — Barcodes & QR Codes ──────────────────────────────────────
export type { BarcodeFormat, QRErrorLevel } from './core/pdf-barcode.js';
export {
    encodeCode128, renderCode128,
    ean13CheckDigit, renderEAN13,
    generateQR, renderQR,
    generateDataMatrix, renderDataMatrix,
    encodePDF417, renderPDF417,
    renderBarcode,
} from './core/pdf-barcode.js';

// ── Core — SVG Path Rendering ───────────────────────────────────────
export type { SvgSegment, SvgRenderOptions } from './core/pdf-svg.js';
export { parseSvgPath, renderSvg } from './core/pdf-svg.js';

// ── Core — AcroForm Fields ──────────────────────────────────────────
export type { FormFieldType, FormField, FormWidgetResult, RadioGroupContext } from './core/pdf-form.js';
export { buildFormWidget, buildAcroFormDict, buildAppearanceStreamDict, buildRadioGroupParent, defaultFieldHeight } from './core/pdf-form.js';

// ── Core — Digital Signatures ───────────────────────────────────────
export type { PdfSignOptions } from './core/pdf-signature.js';
export { buildSigDict, signPdfBytes, estimateContentsSize } from './core/pdf-signature.js';

// ── Core — Streaming Output ─────────────────────────────────────────
export type { StreamOptions } from './core/pdf-stream-writer.js';
export {
    validateDocumentStreamable, validateTableStreamable,
    chunkBinaryString, concatChunks, streamByteLength,
    buildDocumentPDFStream, buildPDFStream,
} from './core/pdf-stream-writer.js';

// ── Crypto — Hashing, ASN.1, RSA, ECDSA, X.509, CMS ────────────────
export { sha384, sha512, hmacSha256 } from './crypto/sha.js';
export type { Asn1Node } from './crypto/asn1.js';
export { derDecode, derSequence, derInteger, derOid, derOctetString, derBitString } from './crypto/asn1.js';
export type { RsaPublicKey, RsaPrivateKey } from './crypto/rsa.js';
export { rsaSign, rsaVerify, rsaSignHash, rsaVerifyHash, parseRsaPrivateKey, parseRsaPublicKey } from './crypto/rsa.js';
export type { EcPublicKey, EcPrivateKey } from './crypto/ecdsa.js';
export { ecdsaSign, ecdsaVerify, ecPublicKeyFromPrivate, encodeEcPublicKey, decodeEcPublicKey } from './crypto/ecdsa.js';
export type { X509Name, X509Certificate } from './crypto/x509.js';
export { parseCertificate, verifyCertSignature, isSelfSigned } from './crypto/x509.js';
export type { SignatureAlgorithm, CmsSignOptions } from './crypto/cms.js';
export { buildCmsSignedData, estimateCmsSize } from './crypto/cms.js';
export { initCrypto } from './crypto/index.js';

export { downloadBlob, toBytes, slugify } from './core/pdf-stream.js';

// ── Core — Layout ───────────────────────────────────────────────────
export {
    PG_W, PG_H,
    DEFAULT_MARGINS, DEFAULT_CW,
    DEFAULT_FONT_SIZES, DEFAULT_COLORS, DEFAULT_COLUMNS,
    ROW_H, TH_H, INFO_LN, BAL_H, TITLE_LN, FT_H, HEADER_H,
    PAGE_SIZES,
    computeColumnPositions, resolveLayout, resolveTemplate,
} from './core/pdf-layout.js';

// ── Fonts — Encoding & Loading ──────────────────────────────────────
export { toWinAnsi, pdfString, truncate, helveticaWidth } from './fonts/encoding.js';
export { createEncodingContext } from './core/encoding-context.js';
export { registerFont, registerFonts, loadFontData, hasFontLoader, getRegisteredLangs, clearFontCache, resetFontRegistry } from './fonts/font-loader.js';
export type { FontLoader } from './fonts/font-loader.js';

// ── Shaping — Thai, Bengali, Tamil & Multi-Script ───────────────────
export { shapeThaiText } from './shaping/thai-shaper.js';
export { shapeBengaliText } from './shaping/bengali-shaper.js';
export { shapeTamilText } from './shaping/tamil-shaper.js';
export {
    containsThai, containsArabic, containsHebrew,
    containsBengali, containsTamil,
    isBengaliCodepoint, isTamilCodepoint,
    isCyrillicCodepoint, isGeorgianCodepoint, isArmenianCodepoint,
} from './shaping/script-registry.js';
export { needsUnicodeFont, detectFallbackLangs, detectCharLang } from './shaping/script-detect.js';
export { splitTextByFont } from './shaping/multi-font.js';
export type { FontRun } from './shaping/multi-font.js';

// ── Shaping — BiDi & Arabic/Hebrew ──────────────────────────────────
export type { BidiRun } from './shaping/bidi.js';
export { resolveBidiRuns, containsRTL } from './shaping/bidi.js';
export { shapeArabicText } from './shaping/arabic-shaper.js';

// ── Parser — PDF Reading & Modification ─────────────────────────────
export type { PdfToken, TokenType, PdfTokenizer } from './parser/pdf-tokenizer.js';
export { createTokenizer } from './parser/pdf-tokenizer.js';
export type { PdfRef, PdfStream, PdfDict as ParsedDict, PdfArray as ParsedArray, PdfValue, PdfIndirectObject } from './parser/pdf-object-parser.js';
export {
    isRef, isStream, isDict, isArray,
    dictGet, dictGetName, dictGetNum, dictGetRef, dictGetDict, dictGetArray,
    parseValue, parseIndirectObject,
} from './parser/pdf-object-parser.js';
export type { XrefEntry, XrefTable } from './parser/pdf-xref-parser.js';
export { findStartxref, parseXrefTable, getTrailerValue, getTrailerRef } from './parser/pdf-xref-parser.js';
export type { PdfReader } from './parser/pdf-reader.js';
export { openPdf } from './parser/pdf-reader.js';
export type { PdfModifier } from './parser/pdf-modifier.js';
export { createModifier } from './parser/pdf-modifier.js';
export { inflateSync, setInflateImpl, initNodeDecompression as initNodeDecompression_parser } from './parser/pdf-inflate.js';

// ── Worker — Off-Thread Generation ──────────────────────────────────
export { createPDF, generatePDFInWorker, generatePDFMainThread, WORKER_THRESHOLD, WORKER_TIMEOUT_MS } from './worker/worker-api.js';
