/**
 * pdfnative — Pure Native PDF Generation Library
 * =================================================
 * Zero-dependency PDF generation for Node.js and browsers.
 * ISO 32000-1 (PDF 1.4) compliant output.
 *
 * Features:
 *   - Pure JavaScript, no vendor dependencies
 *   - A4 table-based PDF with headers, data rows, pagination
 *   - Built-in Helvetica (Latin/WinAnsi) — no font embedding needed
 *   - CIDFont Type2/Identity-H embedding for Unicode scripts
 *   - Thai OpenType shaping (GSUB + GPOS)
 *   - Multi-font cross-script fallback
 *   - TTF font subsetting (dramatic size reduction)
 *   - Web Worker support for large datasets
 *   - Tree-shakeable ESM + CJS dual build
 *
 * @example
 * ```ts
 * import { buildPDFBytes, downloadBlob } from 'pdfnative';
 *
 * const pdf = buildPDFBytes({
 *   title: 'Monthly Report',
 *   infoItems: [{ label: 'Period', value: 'January 2026' }],
 *   balanceText: 'Balance: $1,234.56',
 *   countText: '42 transactions',
 *   headers: ['Date', 'Description', 'Category', 'Amount', 'Status'],
 *   rows: [
 *     { cells: ['01/15', 'Grocery Store', 'Food', '-$45.00', ''], type: 'debit', pointed: false },
 *     { cells: ['01/16', 'Salary', 'Income', '+$3,000.00', 'X'], type: 'credit', pointed: true },
 *   ],
 *   footerText: 'Generated by MyApp',
 * });
 *
 * downloadBlob(pdf, 'report.pdf');
 * ```
 *
 * @packageDocumentation
 */

// ── Types ────────────────────────────────────────────────────────────
export type {
    FontMetrics,
    FontData,
    FontEntry,
    ShapedGlyph,
    TextRun,
    EncodingContext,
    PdfRow,
    PdfInfoItem,
    PdfParams,
    PdfColors,
    ColumnDef,
    PdfLayoutOptions,
    WorkerInputMessage,
    WorkerOutputMessage,
} from './types/pdf-types.js';

// ── Core — PDF Builder ──────────────────────────────────────────────
export { buildPDF, buildPDFBytes } from './core/pdf-builder.js';
export { downloadBlob, toBytes, slugify } from './core/pdf-stream.js';
export { txt, txtR, txtC, txtShaped, fmtNum } from './core/pdf-text.js';

// ── Core — Layout ───────────────────────────────────────────────────
export {
    PG_W, PG_H,
    DEFAULT_MARGINS, DEFAULT_CW,
    DEFAULT_FONT_SIZES, DEFAULT_COLORS, DEFAULT_COLUMNS,
    ROW_H, TH_H, INFO_LN, BAL_H, TITLE_LN, FT_H,
    computeColumnPositions, resolveLayout,
} from './core/pdf-layout.js';

// ── Fonts — Encoding & Loading ──────────────────────────────────────
export { toWinAnsi, pdfString, truncate, helveticaWidth, createEncodingContext } from './fonts/encoding.js';
export { registerFont, registerFonts, loadFontData, hasFontLoader, getRegisteredLangs, clearFontCache, resetFontRegistry } from './fonts/font-loader.js';
export type { FontLoader } from './fonts/font-loader.js';
export { base64ToByteString, buildToUnicodeCMap, buildSubsetWidthArray } from './fonts/font-embedder.js';
export { subsetTTF, ttfChecksum } from './fonts/font-subsetter.js';

// ── Shaping — Thai & Multi-Script ───────────────────────────────────
export { shapeThaiText, buildThaiClusters, containsThai, THAI_START, THAI_END } from './shaping/thai-shaper.js';
export { needsUnicodeFont, detectFallbackLangs } from './shaping/script-detect.js';
export { splitTextByFont } from './shaping/multi-font.js';
export type { FontRun } from './shaping/multi-font.js';

// ── Worker — Off-Thread Generation ──────────────────────────────────
export { createPDF, generatePDFInWorker, generatePDFMainThread, WORKER_THRESHOLD, WORKER_TIMEOUT_MS } from './worker/worker-api.js';
